// AUTO-GENERATED by scripts/extract.mjs from "Forest Quest.dc.html" — do not edit by hand.
// The body below is the design document's game-logic class, lifted verbatim.
// Re-generate with:  npm run extract
import React from 'react';
import { DCLogic } from './dcLogic';
// React Native patch: stub window/document globals used by original web logic
const _noop = () => {};

class Component extends DCLogic {
  creatureOrder = ['pip','mimi','tomo','luma','nori','sol'];

  creatures = {
    pip:{ name:'Pip', species:'Meadow Fox', biome:'Whispering Meadow', archetype:'The Best Friend',
      personality:'Curious, enthusiastic, and a little clumsy — always thrilled to discover. Your first companion and the easiest bond to build.',
      voice:'High energy, warm, slightly squeaky', body:'#E8822F', glow:'#FFC58C', accent:'#5E9A57',
      passiveName:'Scent Trail', passiveDesc:'Highlights hidden collectibles nearby with a faint golden glow.',
      activeName:'Fox Dash', activeBond:20, activeDesc:'A 1.5s speed burst that phases through soft obstacles. 8s cooldown.',
      stages:[{name:'Kit',desc:'Small, uncertain; scarf drags on the ground.'},{name:'Adult Fox',desc:'Fuller tail with silver tips, scarf upgraded to a badge.'},{name:'Elder',desc:'Glowing paw prints and a silver-tipped tail trailing magic.'}],
      lines:[{tag:'Discovery',text:"Ooh! Ooh! I've seen something like this near the berry patch! Try the colours!"},{tag:'Solve',text:"YES! I KNEW you'd get it! You are SO incredibly smart!"},{tag:'On return',text:"I saved you a flower! It's a little squished but it's still pretty!"}],
      milestones:[{at:10,t:'Pip\u2019s Den unlocks in the Sanctuary.'},{at:20,t:'Fox Dash ability \u2014 "I practiced so I could show you!"'},{at:60,t:'Stage 2 evolution \u2014 "I feel different. Do I look taller?"'},{at:100,t:'Stage 3 + the "Best Friends" cinematic.'}],
      discovery:["Ooh! Ooh! I've seen something like this near the berry patch! Try the colours!","I bet there's something sparkly on the other side. Let's solve it!"],
      solve:["YES! I KNEW you'd get it! You are SO incredibly smart!","HA! Did you see that?! We are UNSTOPPABLE!"],
      fail:["That's okay\u2026 maybe we try the other thing first?","The forest wants us to find the tricky way first. It's a TEACHING forest."] },

    mimi:{ name:'Mimi', species:'River Otter', biome:'Babbling Brook', archetype:'The Comedian',
      personality:'Playful, mischievous, and pun-loving. She turns failure into laughter and keeps every session light.',
      voice:'Bubbly, fast-talking, with a giggle at the end', body:'#7A4A22', glow:'#C99A6A', accent:'#4FB8CE',
      passiveName:'Water Slide', passiveDesc:'Water surfaces become frictionless; swim speed +40%.',
      activeName:'Bubble Shield', activeBond:20, activeDesc:'A 5s bubble absorbs one hit. 15s cooldown.',
      stages:[{name:'Pup',desc:'Chubby otter pup with oversized paws and a waterlogged satchel.'},{name:'Sleek Otter',desc:'Adult form; satchel earns its first shell badge.'},{name:'Glow-belly',desc:'Bioluminescent underbelly ripples like water as she moves.'}],
      lines:[{tag:'Discovery',text:"Water flows downhill. Always. Even when the puzzle is UPHILL. Remember that!"},{tag:'Solve',text:"SPLASH! That's my victory noise! Ignore the neighbours."},{tag:'On return',text:"I kept a fish for you! It is a gift fish. A preserved gift fish."}],
      milestones:[{at:10,t:'Mimi\u2019s riverside den joins the Sanctuary.'},{at:20,t:'Bubble Shield ability unlocks.'},{at:60,t:'Stage 2 \u2014 sleek swimming form.'},{at:100,t:'Stage 3 + the "River Song" cinematic.'}],
      discovery:["Is this a sound one? I love the sound ones. I have EXCELLENT ears. That's a fact.","I think \u2014 and thinking is NOT my strong suit \u2014 the blue goes first."],
      solve:["SPLASH! That's my victory noise!","Add it to the Trophy Wall! The Trophy Wall is my brain but still."],
      fail:["I tried this exact thing with a fish once. The fish was also wrong.","Start over \u2014 that pebble clearly has opinions."] },

    tomo:{ name:'Tomo', species:'Mountain Bear', biome:'Mossy Hollow', archetype:'The Mentor',
      personality:'Calm, wise, and thoughtful. He speaks slowly in short sentences and gives the most useful hints — never panicking.',
      voice:'Deep, warm baritone, deliberate', body:'#7B4A2D', glow:'#C29A6A', accent:'#4A7C59',
      passiveName:'Bear Sense', passiveDesc:'Reads your stress and quietly tunes puzzle difficulty to keep you flowing.',
      activeName:'Ground Slam', activeBond:20, activeDesc:'Stuns nearby obstacles 3s and reveals hidden path tiles. 20s cooldown.',
      stages:[{name:'Cub',desc:'Fluffy cub; hat too big, glasses always slipping.'},{name:'Adolescent',desc:'Hat fits now; journal full of bookmarks.'},{name:'Majestic',desc:'Bioluminescent moss glows softly along his back.'}],
      lines:[{tag:'Discovery',text:"Interesting. [Long pause] Yes. I believe\u2026 the middle piece moves first."},{tag:'Solve',text:"Correct. As expected. [He was not at all certain.]"},{tag:'Idle',text:"Did you know there are 14 types of moss? I do. I've counted."}],
      milestones:[{at:10,t:'Tomo\u2019s study \u2014 with bookshelves \u2014 unlocks.'},{at:20,t:'Ground Slam ability unlocks.'},{at:60,t:'Stage 2 \u2014 the hat finally fits.'},{at:100,t:'Stage 3 + "Mountain Knowledge" cinematic.'}],
      discovery:["Patience. The answer is visible. We simply haven't looked the right direction yet.","My journal has 47 entries about this type of puzzle. Page 12."],
      solve:["I am\u2026 satisfied. That is my strongest praise.","The forest approves. Listen \u2014 that is the sound of approval."],
      fail:["Hmm. Let us reconsider.","That was not the solution. That was information. All information is useful."] },

    luma:{ name:'Luma', species:'Firefly Sprite', biome:'Glow Cavern', archetype:'The Heart',
      personality:'Shy and gentle; she whispers and is terrified of the dark but tries to be brave. The most emotionally resonant guide.',
      voice:'Soft whisper with an occasional tiny squeak', body:'#B07FD6', glow:'#E9C7FF', accent:'#5DADE2',
      passiveName:'Light Path', passiveDesc:'Illuminates dark areas in a 4-tile glow around you.',
      activeName:'Luma Flash', activeBond:20, activeDesc:'Blinds enemies 2s and reveals all hidden objects 5s. 18s cooldown.',
      stages:[{name:'Dim',desc:'Faint glow; one wing slightly torn.'},{name:'Brighter',desc:'Wings patched with tiny leaf pieces.'},{name:'Radiant',desc:'Full rainbow bioluminescence lighting a screen corner.'}],
      lines:[{tag:'Discovery',text:"Ohh\u2026 I think I know\u2026 the light goes there\u2026 maybe?"},{tag:'Solve',text:"You did it! [voice cracks with joy] I'm fine. I'm very happy."},{tag:'On return',text:"I kept the light on for you. I always keep the light on."}],
      milestones:[{at:10,t:'Luma\u2019s Lantern Nook glows into the Sanctuary.'},{at:20,t:'Luma Flash ability unlocks.'},{at:60,t:'Stage 2 \u2014 wings repaired.'},{at:100,t:'Stage 3 + "Light in the Dark" cinematic.'}],
      discovery:["I can light the path if you want. Just say when.","Pattern. The sounds have a pattern. I noticed. [glow goes pink]"],
      solve:["[Glow bursts pure white] You actually \u2014 sorry. I'm very happy.","[a tiny happy loop-de-loop] !!!"],
      fail:["That's okay\u2026 we'll try the other way.","I'm here. We can try again."] },

    nori:{ name:'Nori', species:'Cloud Deer', biome:'Windmill Heights', archetype:'The Visionary',
      personality:'Dreamy and artistic, easily distracted, and notices beauty no one else does. Teaches observational puzzles.',
      voice:'Floaty and melodic, often trailing off', body:'#D8D2E0', glow:'#FFFFFF', accent:'#9B89B4',
      passiveName:'Wind Read', passiveDesc:'Predicts wind in platforming; shows safe jump windows 0.5s early.',
      activeName:'Cloud Step', activeBond:20, activeDesc:'Creates a 4s cloud platform usable as a mid-air double jump. 12s cooldown.',
      stages:[{name:'Fawn',desc:'Soft fading spots; tiny cloud-puff tail.'},{name:'Adolescent',desc:'Fuller antlers wrapped in vines and flowers.'},{name:'Grown',desc:'Silver-glowing antlers; cloud tail shifts colour with weather.'}],
      lines:[{tag:'Discovery',text:"I notice the colours. Do you notice the colours? There's something about them\u2026"},{tag:'Solve',text:"That was\u2026 like when the mist clears. You could see it all at once."},{tag:'Idle',text:"I wrote a poem about this region once. I remember how it made me feel."}],
      milestones:[{at:10,t:'Nori\u2019s Cloud Perch rises in the Sanctuary.'},{at:20,t:'Cloud Step ability unlocks.'},{at:60,t:'Stage 2 \u2014 fuller antlers.'},{at:100,t:'Stage 3 + "Cloud Walker" cinematic.'}],
      discovery:["Wind moves in patterns. Like this puzzle. I think.","\u2026Sorry. Was looking at that leaf. The large piece \u2014 that's where I'd start."],
      solve:["Oh. Yes. I thought it might be that.","The colours settled. That means we got it right. Colours always know."],
      fail:["Hmm. The shape of it isn't quite\u2026 let's drift back a little.","No rush. The wind will come around again."] },

    sol:{ name:'Sol', species:'Ancient Tortoise', biome:'Skyroot Canopy', archetype:'The Sage',
      personality:'Ancient and serene; he speaks rarely and each word feels earned. The rarest companion — players feel honoured to know him.',
      voice:'Low, gravelly, measured \u2014 each word a gift', body:'#5A6450', glow:'#9FB08A', accent:'#F5A623',
      passiveName:'Ancient Memory', passiveDesc:'Remembers every puzzle type; grants one extra hint in new zones.',
      activeName:'Shell Shelter', activeBond:20, activeDesc:'Hide inside his shell up to 5s of full invincibility. 30s cooldown.',
      stages:[{name:'Younger',desc:'Still ancient, shell less decorated, four amber runes.'},{name:'Elder',desc:'More runes; a tiny bird nest rests on his shell.'},{name:'World-Shell',desc:'A full ecosystem \u2014 waterfall, fireflies, a tiny shrine.'}],
      lines:[{tag:'Discovery',text:"\u2026Patience. The answer has been here longer than you have."},{tag:'Solve',text:"\u2026Yes. You did well."},{tag:'When you struggle',text:"You are not failing. You are learning. These are not the same."}],
      milestones:[{at:20,t:'Shell Shelter ability unlocks.'},{at:60,t:'Stage 2 \u2014 shell runes begin to glow.'},{at:80,t:'Sol\u2019s personal quest: "Sol\u2019s Teaching".'},{at:100,t:'Sol\u2019s Ancient Hollow + "The Ancient Bond" cinematic.'}],
      discovery:["Think of the tree. Which root grows first? Follow the root.","The young make it complex. It is simple. Breathe. Look. See."],
      solve:["The forest remembers this moment. It is now part of its long story.","Wisdom takes root slowly. Today, a small root formed."],
      fail:["There is no wrong direction in the forest. Only directions not yet tried.","I failed this puzzle for forty years. Then I tried differently."] }
  };

  regions = [
    { id:'meadow', num:1, name:'Whispering Meadow', guide:'pip', difficulty:'Introductory', unlock:'Start', unlocked:true, x:13, y:80, pct:60,
      sky:'#FBE7B8', primary:'#7BC67E', secondary:'#F5A623', accent:'#FFB7C5', glow:'#FFE9A8', ground:'#6BA86E', groundDark:'#4d8056', dark:false,
      desc:'Sun-drenched fields of tall grass and wildflowers under a golden-hour sky. Cheerful, open, and inviting \u2014 the first steps of every journey.',
      biome:'Flower patches \u00b7 hay bales \u00b7 ponds \u00b7 little windmills', puzzleType:'colour', puzzleName:'Colour Match',
      collectibles:'8 Butterflies \u00b7 3 Hay Bundles \u00b7 1 Legend Scroll', boss:'The Tangle Vine', puzzles:['colour','shape'] },
    { id:'brook', num:2, name:'Babbling Brook', guide:'mimi', difficulty:'Easy', unlock:'Solve 10 Meadow puzzles', unlocked:true, x:30, y:63, pct:25,
      sky:'#CFEFF4', primary:'#4FB8CE', secondary:'#FFFFFF', accent:'#6B8E5C', glow:'#D6F5FA', ground:'#3E94A8', groundDark:'#2e7185', dark:false,
      desc:'A sparkling brook of stepping stones, weeping willows, and water lilies. Cool, playful, and always moving downstream.',
      biome:'Waterfalls \u00b7 lily pads \u00b7 log bridges \u00b7 jumping frogs', puzzleType:'flow', puzzleName:'Flow Direction',
      collectibles:'6 Pebbles \u00b7 4 Shells \u00b7 1 Brook Rune', boss:'The Mudslide Gorgon', puzzles:['flow'] },
    { id:'hollow', num:3, name:'Mossy Hollow', guide:'tomo', difficulty:'Easy\u2013Medium', unlock:'Explorer Rank 3', unlocked:true, x:19, y:44, pct:0,
      sky:'#9FC9A8', primary:'#3D6B45', secondary:'#7AFCD0', accent:'#8B6355', glow:'#bdf5dc', ground:'#2F543A', groundDark:'#1f3a28', dark:false,
      desc:'Ancient forest floor with enormous roots and bioluminescent mushrooms that glow at night. Deep greens and earthy browns.',
      biome:'Mushroom trampolines \u00b7 root tunnels \u00b7 firefly swarms', puzzleType:'memory', puzzleName:'Memory Match',
      collectibles:'10 Mushroom Caps \u00b7 2 Ancient Acorns \u00b7 1 Carving', boss:'The Slumber Root', puzzles:['memory'] },
    { id:'shore', num:4, name:'Crystal Shore', guide:'pip', difficulty:'Medium', unlock:'Explorer Rank 5', unlocked:false, x:41, y:81, pct:0,
      sky:'#CFF3F7', primary:'#80DEEA', secondary:'#FFF59D', accent:'#F48FB1', glow:'#e3fbff', ground:'#5fb9c6', groundDark:'#3f97a4', dark:false,
      desc:'Coastal cliffs with crystal formations that catch the light. Turquoise water, white sand, and a pink sunset palette.',
      biome:'Crystal stalagmites \u00b7 tide pools \u00b7 sandbars', puzzleType:'light', puzzleName:'Light Refraction',
      collectibles:'12 Crystal Shards \u00b7 3 Driftwood Messages \u00b7 1 Mural', boss:'The Tide Warden', puzzles:['light'] },
    { id:'cavern', num:5, name:'Glow Cavern', guide:'luma', difficulty:'Medium', unlock:'Explorer Rank 7', unlocked:false, x:51, y:55, pct:0,
      sky:'#2A0B4A', primary:'#3a1566', secondary:'#7B1FA2', accent:'#E040FB', glow:'#b765e0', ground:'#1f0a3a', groundDark:'#12052a', dark:true,
      desc:'An underground network, pitch-black except for bioluminescent plants and Luma\u2019s glow. The most atmospheric zone.',
      biome:'Dark sections \u00b7 glowing rope vines \u00b7 underground lake', puzzleType:'shadow', puzzleName:'Shadow Match',
      collectibles:'8 Glowstone Gems \u00b7 5 Crystal Clusters \u00b7 1 Rune Tablet', boss:'The Shadow Wisp King', puzzles:['shadow'] },
    { id:'canopy', num:6, name:'Autumn Canopy', guide:'tomo', difficulty:'Medium', unlock:'Explorer Rank 9', unlocked:false, x:63, y:73, pct:0,
      sky:'#FFD9A6', primary:'#FF7043', secondary:'#FFCA28', accent:'#8D6E63', glow:'#ffd9a0', ground:'#c75a33', groundDark:'#9c4525', dark:false,
      desc:'Enormous ancient trees in orange, red, and gold. Wind-swept, warm, and full of melancholy beauty.',
      biome:'Swinging branches \u00b7 leaf tornados \u00b7 acorn cannons', puzzleType:'pattern', puzzleName:'Pattern Trace',
      collectibles:'15 Autumn Leaves \u00b7 2 Bark Tokens \u00b7 1 Tapestry', boss:'The Gale Stag', puzzles:['pattern'] },
    { id:'heights', num:7, name:'Windmill Heights', guide:'nori', difficulty:'Medium\u2013Hard', unlock:'Explorer Rank 12', unlocked:false, x:59, y:35, pct:0,
      sky:'#DDF1FB', primary:'#B3E5FC', secondary:'#FFFFFF', accent:'#A5D6A7', glow:'#eafaff', ground:'#8fc79a', groundDark:'#6da877', dark:false,
      desc:'A high-altitude meadow of giant windmills, floating cloud platforms, and sky-high views. Light, airy, adventurous.',
      biome:'Cloud platforms \u00b7 windmill blades \u00b7 thermal vents', puzzleType:'sequence', puzzleName:'Sequence Order',
      collectibles:'10 Cloud Wisps \u00b7 4 Windmill Cogs \u00b7 1 Banner', boss:'The Storm Vane', puzzles:['sequence','slide'] },
    { id:'roots', num:8, name:'Ancient Roots', guide:'sol', difficulty:'Hard', unlock:'Explorer Rank 15', unlocked:false, x:77, y:50, pct:0,
      sky:'#2E5A33', primary:'#1B5E20', secondary:'#E65100', accent:'#FFF9C4', glow:'#5a9c5f', ground:'#163E1A', groundDark:'#0d2810', dark:true,
      desc:'The deepest, oldest part of the forest \u2014 roots older than history, glowing runes everywhere. Mystical and vast.',
      biome:'Root bridges \u00b7 rune doors \u00b7 memory pools \u00b7 gravity flips', puzzleType:'rune', puzzleName:'Rune Translation',
      collectibles:'6 Rune Stones \u00b7 3 Root Cores \u00b7 1 Legend Scroll', boss:'The First Guardian', puzzles:['rune','hanoi'] },
    { id:'highlands', num:9, name:'Monsoon Highlands', guide:'mimi', difficulty:'Hard', unlock:'Explorer Rank 18', unlocked:false, x:81, y:78, pct:0,
      sky:'#6E8AAE', primary:'#1565C0', secondary:'#37474F', accent:'#FFD54F', glow:'#7fa6d6', ground:'#2C3A4A', groundDark:'#1c2632', dark:true,
      desc:'Dramatic rain-soaked highlands with waterfalls everywhere and dynamic, dangerous weather.',
      biome:'Flash-flood escapes \u00b7 water spouts \u00b7 rainbow bridges', puzzleType:'weight', puzzleName:'Weight Balance',
      collectibles:'8 Rainwater Crystals \u00b7 4 Highland Seeds \u00b7 1 Carving', boss:'The Deluge', puzzles:['weight','number'] },
    { id:'skyroot', num:10, name:'Skyroot Canopy', guide:'sol', difficulty:'Master', unlock:'Rank 22 + all regions', unlocked:false, x:85, y:23, pct:0,
      sky:'#FBF1CF', primary:'#FFE9A8', secondary:'#1A237E', accent:'#FFD700', glow:'#FFF6DA', ground:'#e8ddb0', groundDark:'#c9bb8a', dark:false,
      desc:'The very top of the world\u2019s oldest tree, above the clouds. Stars visible even by day; gold and white light everywhere.',
      biome:'Cloud sea \u00b7 star platforms \u00b7 Sol\u2019s Ancient Library', puzzleType:'sound', puzzleName:'Sound Pattern',
      collectibles:'The Heartstone \u00b7 star fragments \u00b7 final cinematic', boss:'The Forgetting', puzzles:['sound','matrix','eqn'] },
    { id:'stardust', num:11, name:'Stardust Vale', guide:'nori', difficulty:'Cosmic', unlock:'Complete Skyroot Canopy', unlocked:false, x:64, y:11, pct:0,
      sky:'#11375f', primary:'#1f5184', secondary:'#FFD86B', accent:'#9FC8FF', glow:'#CFE2FF', ground:'#143a5e', groundDark:'#0a1f3a', dark:true,
      desc:'A hidden vale above the clouds where fallen stars rest in the grass. Trace the constellations to wake the sleeping sky and complete the forest\u2019s story.',
      biome:'Star meadows \u00b7 constellation pools \u00b7 drifting comets', puzzleType:'dots', puzzleName:'Connecting Dots',
      collectibles:'9 Star Shards \u00b7 3 Comet Tails \u00b7 1 Sky Map', boss:'The Long Night', puzzles:['dots'] }
  ];

  // ---- Region puzzle ladders: 10 DISTINCT puzzles per region (110 total).
  // Order = 3 Easy (E) -> 4 Medium (M) -> 3 Hard (H). Every puzzle has a unique themed name. ----
  regionPuzzles = {
    meadow: [
      {t:'colour',n:'Petal Sort',d:'E'},{t:'shape',n:'Acorn Pegs',d:'E'},{t:'word',n:'Bloom Spell',d:'E'},
      {t:'pattern',n:'Firefly Trail',d:'M'},{t:'sequence',n:'Sprout Order',d:'M'},{t:'flow',n:'Dewdrop Run',d:'M'},{t:'light',n:'Sunbeam Bend',d:'M'},
      {t:'number',n:'Beehive Count',d:'H'},{t:'slide',n:'Haybale Shuffle',d:'H'},{t:'matrix',n:'Meadow Memory',d:'H'} ],
    brook: [
      {t:'word',n:'River Spell',d:'E'},{t:'sound',n:'Ripple Echo',d:'E'},{t:'dots',n:'Lily Link',d:'E'},
      {t:'flow',n:'Stream Routing',d:'M'},{t:'weight',n:'Pebble Scales',d:'M'},{t:'sequence',n:'Current Order',d:'M'},{t:'trace',n:'Otter Path',d:'M'},
      {t:'number',n:'Stepping Count',d:'H'},{t:'slide',n:'Stone Slide',d:'H'},{t:'eqn',n:'Waterfall Sums',d:'H'} ],
    hollow: [
      {t:'memory',n:'Mushroom Pairs',d:'E'},{t:'colour',n:'Spore Sort',d:'E'},{t:'sound',n:'Hollow Echo',d:'E'},
      {t:'weight',n:'Root Balance',d:'M'},{t:'pattern',n:'Moss Trace',d:'M'},{t:'rune',n:'Bark Runes',d:'M'},{t:'sequence',n:'Growth Order',d:'M'},
      {t:'matrix',n:'Hollow Grid',d:'H'},{t:'slide',n:'Root Shuffle',d:'H'},{t:'number',n:'Ring Count',d:'H'} ],
    shore: [
      {t:'colour',n:'Shell Sort',d:'E'},{t:'shape',n:'Tidepool Fit',d:'E'},{t:'dots',n:'Star Shells',d:'E'},
      {t:'light',n:'Crystal Beam',d:'M'},{t:'flow',n:'Tide Channels',d:'M'},{t:'trace',n:'Sand Glyph',d:'M'},{t:'sequence',n:'Wave Order',d:'M'},
      {t:'number',n:'Pearl Count',d:'H'},{t:'matrix',n:'Reef Recall',d:'H'},{t:'hanoi',n:'Cairn Stack',d:'H'} ],
    cavern: [
      {t:'memory',n:'Glow Pairs',d:'E'},{t:'word',n:'Crystal Spell',d:'E'},{t:'sound',n:'Cave Echo',d:'E'},
      {t:'shadow',n:'Shadow Cast',d:'M'},{t:'light',n:'Beam Maze',d:'M'},{t:'pattern',n:'Glow Trail',d:'M'},{t:'rune',n:'Cave Runes',d:'M'},
      {t:'matrix',n:'Stalactite Grid',d:'H'},{t:'slide',n:'Boulder Slide',d:'H'},{t:'eqn',n:'Gem Sums',d:'H'} ],
    canopy: [
      {t:'colour',n:'Leaf Sort',d:'E'},{t:'shape',n:'Bark Fit',d:'E'},{t:'dots',n:'Branch Link',d:'E'},
      {t:'pattern',n:'Leaf Trace',d:'M'},{t:'sequence',n:'Falling Order',d:'M'},{t:'weight',n:'Acorn Scales',d:'M'},{t:'trace',n:'Wind Glyph',d:'M'},
      {t:'number',n:'Seed Count',d:'H'},{t:'hanoi',n:'Log Stack',d:'H'},{t:'slide',n:'Canopy Slide',d:'H'} ],
    heights: [
      {t:'sound',n:'Chime Echo',d:'E'},{t:'word',n:'Sky Spell',d:'E'},{t:'dots',n:'Cloud Link',d:'E'},
      {t:'sequence',n:'Cog Order',d:'M'},{t:'flow',n:'Wind Routing',d:'M'},{t:'light',n:'Sky Beam',d:'M'},{t:'trace',n:'Vane Glyph',d:'M'},
      {t:'slide',n:'Gear Slide',d:'H'},{t:'number',n:'Cog Count',d:'H'},{t:'hanoi',n:'Windmill Stack',d:'H'} ],
    roots: [
      {t:'memory',n:'Rune Pairs',d:'E'},{t:'shape',n:'Stone Fit',d:'E'},{t:'word',n:'Old Spell',d:'E'},
      {t:'rune',n:'Rune Reading',d:'M'},{t:'shadow',n:'Idol Shadow',d:'M'},{t:'light',n:'Rune Beam',d:'M'},{t:'weight',n:'Ancient Scales',d:'M'},
      {t:'hanoi',n:'Guardian Stack',d:'H'},{t:'matrix',n:'Memory Pools',d:'H'},{t:'eqn',n:'Root Sums',d:'H'} ],
    highlands: [
      {t:'colour',n:'Crystal Sort',d:'E'},{t:'sound',n:'Thunder Echo',d:'E'},{t:'dots',n:'Rain Link',d:'E'},
      {t:'weight',n:'Flood Scales',d:'M'},{t:'flow',n:'Channel Routing',d:'M'},{t:'trace',n:'Lightning Glyph',d:'M'},{t:'rune',n:'Storm Runes',d:'M'},
      {t:'number',n:'Raindrop Count',d:'H'},{t:'eqn',n:'Deluge Sums',d:'H'},{t:'slide',n:'Mudslide Slide',d:'H'} ],
    skyroot: [
      {t:'sound',n:'Star Echo',d:'E'},{t:'memory',n:'Constellation Pairs',d:'E'},{t:'word',n:'Star Spell',d:'E'},
      {t:'light',n:'Starlight Beam',d:'M'},{t:'sequence',n:'Celestial Order',d:'M'},{t:'shadow',n:'Eclipse Shadow',d:'M'},{t:'trace',n:'Sky Glyph',d:'M'},
      {t:'matrix',n:'Star Grid',d:'H'},{t:'hanoi',n:'Cosmic Stack',d:'H'},{t:'eqn',n:'Astral Sums',d:'H'} ],
    stardust: [
      {t:'dots',n:'Star Link',d:'E'},{t:'colour',n:'Comet Sort',d:'E'},{t:'word',n:'Cosmic Spell',d:'E'},
      {t:'trace',n:'Constellation Draw',d:'M'},{t:'light',n:'Aurora Beam',d:'M'},{t:'pattern',n:'Comet Trail',d:'M'},{t:'rune',n:'Star Runes',d:'M'},
      {t:'number',n:'Galaxy Count',d:'H'},{t:'matrix',n:'Nebula Grid',d:'H'},{t:'eqn',n:'Stardust Sums',d:'H'} ]
  };
  ladderFor(id){ return this.regionPuzzles[id] || [ { t:(this.regions.find(r=>r.id===id)||{}).puzzleType || 'colour', n:'Puzzle', d:'E' } ]; }
  tierMeta(d){ return ({E:{l:'Easy',c:'#5EA862',bg:'#eaf2ec'},M:{l:'Medium',c:'#E8954E',bg:'#fbf0e3'},H:{l:'Hard',c:'#C0392B',bg:'#f7e6e3'}})[d] || {l:'',c:'#999',bg:'#eee'}; }

  puzzleCodexList = [
    { type:'colour', name:'Colour Match', guide:'pip', ageMin:4, ageMax:7, skill:'Colour recognition \u00b7 visual discrimination', color:'#E8654E', colorDark:'#c44a37' },
    { type:'shape', name:'Shape Fit', guide:'pip', ageMin:4, ageMax:8, skill:'Spatial reasoning \u00b7 geometry', color:'#F2B33D', colorDark:'#cf942a' },
    { type:'word', name:'Word Match', guide:'tomo', ageMin:4, ageMax:9, skill:'Early literacy \u00b7 spelling \u00b7 phonics', color:'#3DBE9B', colorDark:'#2a9a7c' },
    { type:'odd', name:'Odd One Out', guide:'pip', ageMin:4, ageMax:7, skill:'Visual discrimination \u00b7 focus', color:'#E89BB0', colorDark:'#c47a8f' },
    { type:'count', name:'Counting Quest', guide:'mimi', ageMin:4, ageMax:8, skill:'Counting \u00b7 early numeracy', color:'#56A0D3', colorDark:'#3f7faa' },
    { type:'maze', name:'Maze Run', guide:'nori', ageMin:6, ageMax:11, skill:'Navigation \u00b7 route planning', color:'#86C166', colorDark:'#67a049' },
    { type:'memory', name:'Memory Match', guide:'tomo', ageMin:4, ageMax:9, skill:'Memory \u00b7 concentration', color:'#6FB36A', colorDark:'#519a4c' },
    { type:'sequence', name:'Sequence Order', guide:'nori', ageMin:5, ageMax:9, skill:'Logical sequence \u00b7 ordering', color:'#5EA862', colorDark:'#427d46' },
    { type:'pattern', name:'Pattern Trace', guide:'tomo', ageMin:5, ageMax:9, skill:'Visual memory \u00b7 fine motor', color:'#4FB8CE', colorDark:'#3a94a8' },
    { type:'sound', name:'Sound Pattern', guide:'sol', ageMin:5, ageMax:10, skill:'Auditory memory \u00b7 sequencing', color:'#8E6FC9', colorDark:'#6f52a8' },
    { type:'trace', name:'Glyph Trace', guide:'nori', ageMin:6, ageMax:12, skill:'Drawing \u00b7 motor planning \u00b7 shape tracing', color:'#E0A93B', colorDark:'#bd8a25' },
    { type:'flow', name:'Flow Direction', guide:'mimi', ageMin:6, ageMax:10, skill:'Spatial logic \u00b7 cause-and-effect', color:'#4F91C9', colorDark:'#3a72a8' },
    { type:'weight', name:'Weight Balance', guide:'mimi', ageMin:6, ageMax:11, skill:'Estimation \u00b7 early numeracy', color:'#E89B5A', colorDark:'#c47a3c' },
    { type:'rune', name:'Rune Translation', guide:'sol', ageMin:7, ageMax:12, skill:'Symbol recognition \u00b7 early literacy', color:'#E65100', colorDark:'#b53f00' },
    { type:'light', name:'Light Refraction', guide:'pip', ageMin:8, ageMax:12, skill:'Angle estimation \u00b7 spatial reasoning', color:'#E040FB', colorDark:'#b51fcf' },
    { type:'shadow', name:'Shadow Match', guide:'luma', ageMin:8, ageMax:12, skill:'3D spatial reasoning \u00b7 perspective', color:'#7B6FA8', colorDark:'#5a5188' },
    { type:'number', name:'Number Sequence', guide:'tomo', ageMin:12, ageMax:16, skill:'Numeric reasoning \u00b7 pattern logic', color:'#2E8BC0', colorDark:'#1f6a96', hard:true },
    { type:'matrix', name:'Memory Matrix', guide:'sol', ageMin:12, ageMax:16, skill:'Working memory \u00b7 spatial recall', color:'#11998E', colorDark:'#0c7068', hard:true },
    { type:'slide', name:'Sliding Tiles', guide:'nori', ageMin:14, ageMax:99, skill:'Spatial planning \u00b7 sequencing', color:'#C0392B', colorDark:'#922b21', hard:true },
    { type:'hanoi', name:'Tower of Hanoi', guide:'tomo', ageMin:16, ageMax:99, skill:'Recursive planning \u00b7 foresight', color:'#6C3483', colorDark:'#4a2359', hard:true },
    { type:'eqn', name:'Equation Forge', guide:'sol', ageMin:18, ageMax:99, skill:'Mental arithmetic \u00b7 deduction', color:'#B9770E', colorDark:'#8a590a', hard:true },
    { type:'dots', name:'Connecting Dots', guide:'nori', ageMin:4, ageMax:99, skill:'Number order \u00b7 visual tracking', color:'#5B6CE0', colorDark:'#3f4cb0' }
  ];

  // ---- Seasonal event: Monsoon Magic ----
  eventTrialDefs = [
    { id:'flood',  name:'Flood Gates',     type:'flow',     guide:'mimi', pearls:12, sub:'Route the monsoon water' },
    { id:'recall', name:'Storm Recall',    type:'sound',    guide:'luma', pearls:12, sub:'Echo the rolling thunder' },
    { id:'rising', name:'Rising Waters',   type:'count',    guide:'mimi', pearls:12, sub:'Count the falling raindrops' },
    { id:'bridge', name:'Rainbow Bridge',  type:'sequence', guide:'nori', pearls:14, sub:'Order the rainbow bands' },
    { id:'glyph',  name:'The Deluge Glyph',type:'trace',    guide:'sol',  pearls:16, sub:'Trace the great storm sigil' }
  ];
  eventShopDefs = [
    { id:'cloak',   name:'Monsoon Cloak', sub:'Avatar rain trail',   cost:30, color:'linear-gradient(160deg,#6E8AAE,#1565C0)' },
    { id:'lantern', name:'Storm Lantern', sub:'Sanctuary light',     cost:25, color:'linear-gradient(160deg,#FFE7A8,#FFD54F)' },
    { id:'arch',    name:'Rainbow Arch',  sub:'Sanctuary decoration',cost:45, color:'linear-gradient(160deg,#E89BB0,#86C166)' }
  ];

  // ---- Daily login chest (streak-free) ----
  dailyRewards = [
    { day:1, label:'30 Acorns',           kind:'acorns', amt:30,  icon:'\ud83c\udf30' },
    { day:2, label:'10 Glow Dust',        kind:'glow',   amt:10,  icon:'\ud83c\udf44' },
    { day:3, label:'50 Acorns',           kind:'acorns', amt:50,  icon:'\ud83c\udf42' },
    { day:4, label:'A Decoration',        kind:'glow',   amt:5,   icon:'\ud83c\udf3f' },
    { day:5, label:'80 Acorns',           kind:'acorns', amt:80,  icon:'\ud83e\udd8b' },
    { day:6, label:'25 Glow Dust',        kind:'glow',   amt:25,  icon:'\ud83c\udf38' },
    { day:7, label:'200 Acorns + Card',   kind:'acorns', amt:200, icon:'\ud83c\udf81' }
  ];
  // ---- Parent dashboard skill mapping ----
  skillOf(t){ return ({ colour:'Visual', odd:'Visual', shape:'Visual',
    word:'Literacy', rune:'Literacy',
    memory:'Memory', matrix:'Memory', pattern:'Memory', sound:'Memory',
    count:'Numeracy', number:'Numeracy', eqn:'Numeracy', weight:'Numeracy',
    sequence:'Logic', flow:'Logic', hanoi:'Logic', slide:'Logic', light:'Logic', shadow:'Logic', dots:'Logic', maze:'Logic',
    trace:'Motor' })[t] || 'Logic'; }
  skillColors = { Visual:'#E8654E', Literacy:'#3DBE9B', Memory:'#8E6FC9', Numeracy:'#56A0D3', Logic:'#5EA862', Motor:'#E0A93B' };

  ranks = [
    { num:1, name:'Seedling', xp:0 }, { num:2, name:'Sprout', xp:100 }, { num:3, name:'Sapling', xp:250 },
    { num:5, name:'Leaf Finder', xp:600 }, { num:7, name:'Trail Walker', xp:1200 }, { num:10, name:'Path Maker', xp:2500 },
    { num:12, name:'Forest Friend', xp:4000 }, { num:15, name:'Grove Keeper', xp:7000 }, { num:18, name:'Canopy Climber', xp:12000 },
    { num:22, name:'Sky Wanderer', xp:20000 }, { num:25, name:'Forest Legend', xp:35000 }
  ];

  quests = [
    { type:'Quick Quest', title:'Find 3 butterflies in the Meadow', reward:'+15 Acorns', pct:66, color:'#F5A623' },
    { type:'Puzzle Quest', title:'Solve 2 Colour Match puzzles', reward:'+10 Glow Dust', pct:50, color:'#9B59B6' },
    { type:'Bond Quest', title:'Spend time with Pip 3 times', reward:'+20 XP', pct:33, color:'#5EA862' }
  ];

  scrapbook = [
    { label:'Meadow', bg:'linear-gradient(160deg,#7BC67E,#F5A623)', earned:true },
    { label:'Pip Bond 20', bg:'linear-gradient(160deg,#E8822F,#FFC58C)', earned:true },
    { label:'Brook', bg:'linear-gradient(160deg,#4FB8CE,#6B8E5C)', earned:true },
    { label:'First Solve', bg:'linear-gradient(160deg,#F2B33D,#E89B5A)', earned:true },
    { label:'Hollow', bg:'linear-gradient(160deg,#3D6B45,#7AFCD0)', earned:false },
    { label:'Cavern', bg:'linear-gradient(160deg,#3a1566,#E040FB)', earned:false },
    { label:'Shore', bg:'linear-gradient(160deg,#4F91C9,#F2D49B)', earned:false },
    { label:'Canopy', bg:'linear-gradient(160deg,#4FB8CE,#86C166)', earned:false }
  ];

  decor = [
    { name:'Flower Bush', cost:'50', color:'linear-gradient(160deg,#FFB7C5,#7BC67E)' },
    { name:'Lantern Post', cost:'120', color:'linear-gradient(160deg,#FFE7A8,#F5A623)' },
    { name:'Small Pond', cost:'180', color:'linear-gradient(160deg,#A8D8EA,#4FB8CE)' },
    { name:'Firefly Jar', cost:'220', color:'linear-gradient(160deg,#E9C7FF,#9B59B6)' },
    { name:'Wind Chime', cost:'90', color:'linear-gradient(160deg,#FFFFFF,#A5D6A7)' }
  ];

  state = {
    screen:'title',
    acorns:140, glowDust:12, xp:650, rank:5,
    bonds:{ pip:45, mimi:18, tomo:8, luma:0, nori:0, sol:0 },
    currentRegion:'meadow', exploreProgress:0, gotCollectible:false, avatarLine:'',
    unlocked:{ meadow:true, brook:true, hollow:true, shore:false, cavern:false, canopy:false, heights:false, roots:false, highlands:false, skyroot:false, stardust:false },
    riOpen:false, riRegion:null,
    puzzleType:null, puzzleGuide:null, puzzleFromCodex:false, inLadder:false, regionLadder:null, regionStage:0, hintOpen:false, attempts:0, hintText:'',
    cm:null, mem:null, flow:null, pat:null, snd:null, shp:null, wgt:null, lgt:null, seq:null, shd:null, rune:null, num:null, mtx:null, slide:null, hanoi:null, eqn:null, dots:null, rw:null,
    detailId:'pip', detailLine:'',
    quests:[
      { id:'q_collect', type:'Quick Quest', title:'Find 3 forest treasures', target:3, prog:1, vIdx:0, color:'#F5A623', kind:'acorns', amt:15, claimed:false },
      { id:'q_solve', type:'Puzzle Quest', title:'Solve 3 puzzles today', target:3, prog:0, vIdx:0, color:'#9B59B6', kind:'glow', amt:10, claimed:false },
      { id:'q_bond', type:'Bond Quest', title:'Spend time with a friend 3 times', target:3, prog:0, vIdx:0, color:'#5EA862', kind:'xp', amt:40, claimed:false }
    ],
    gifts:{ pip:true, mimi:true, tomo:false, luma:false, nori:false, sol:false },
    finaleStage:0,
    rainPearls:0, eventDone:{}, eventOwned:{}, eventTrial:null,
    puzzlesSolved:0, minutesPlayed:120,
    dailyShown:false, dailyClaimed:null, dailyOpen:false,
    skills:{ Visual:8, Memory:6, Numeracy:5, Logic:7, Literacy:3, Motor:2 },
    boss:null, bossPendingRegion:null,
    toast:null
  };

  componentDidMount(){
    // React Native: no DOM scaling needed — screen fills device natively
  }
  componentWillUnmount(){ /* no-op */ }

  // ---------- helpers ----------
  pick(arr){ return arr[Math.floor(Math.random()*arr.length)]; }
  shuffle(a){ a=a.slice(); for(let i=a.length-1;i>0;i--){ const j=Math.floor(Math.random()*(i+1)); [a[i],a[j]]=[a[j],a[i]]; } return a; }
  go(s){ this.setState({ screen:s, riOpen:false }); }
  exitPuzzle(){ if(this.state.eventTrial){ this.setState({eventTrial:null}); this.go('event'); return; } this.go(this.state.puzzleFromCodex ? 'journey' : 'map'); }
  showToast(t){ this.setState({toast:t}); clearTimeout(this._tt); this._tt=setTimeout(()=>this.setState({toast:null}),2200); }
  region(){ return this.regions.find(r=>r.id===this.state.currentRegion) || this.regions[0]; }
  guideOf(rid){ return this.creatures[this.regions.find(r=>r.id===rid).guide]; }
  questPools = {
    q_collect:[ {title:'Find 3 forest treasures', target:3, kind:'acorns', amt:15},
                {title:'Gather 4 hidden treasures', target:4, kind:'acorns', amt:22},
                {title:'Collect 5 treasures on your travels', target:5, kind:'acorns', amt:30} ],
    q_solve:[ {title:'Solve 3 puzzles today', target:3, kind:'glow', amt:10},
              {title:'Crack 4 puzzles', target:4, kind:'glow', amt:15},
              {title:'Master 5 puzzles in a row', target:5, kind:'glow', amt:22} ],
    q_bond:[ {title:'Spend time with a friend 3 times', target:3, kind:'xp', amt:40},
             {title:'Bond with friends 4 times', target:4, kind:'xp', amt:55},
             {title:'Share 5 moments with friends', target:5, kind:'xp', amt:75} ]
  };
  tickQuest(matchKind){
    let toast=null;
    const quests=this.state.quests.map(q=>{
      const isMatch = (q.id==='q_collect'&&matchKind==='collect') || (q.id==='q_solve'&&matchKind==='solve') || (q.id==='q_bond'&&matchKind==='bond');
      if(!isMatch || q.claimed || q.prog>=q.target) return q;
      const prog=q.prog+1; const done=prog>=q.target;
      if(done){ toast='Quest complete: '+q.title+'  +'+q.amt+' '+(q.kind==='acorns'?'Acorns':q.kind==='glow'?'Glow Dust':'XP'); }
      return {...q, prog, claimed: done };
    });
    const justDone=quests.find((q,i)=>q.claimed && !this.state.quests[i].claimed);
    this.setState(s=>{ const patch={ quests }; if(justDone){ if(justDone.kind==='acorns')patch.acorns=s.acorns+justDone.amt; else if(justDone.kind==='glow')patch.glowDust=s.glowDust+justDone.amt; else if(justDone.kind==='xp'){ patch.xp=s.xp+justDone.amt; patch.rank=this.rankForXp(s.xp+justDone.amt).num; } } return patch; });
    if(toast) setTimeout(()=>this.showToast(toast), 400);
    if(justDone){ clearTimeout(this['_q_'+justDone.id]); this['_q_'+justDone.id]=setTimeout(()=>this.refreshQuest(justDone.id), 1700); }
  }
  refreshQuest(id){
    const pool=this.questPools[id]; if(!pool) return;
    this.setState(s=>{
      const quests=s.quests.map(q=>{
        if(q.id!==id) return q;
        const nextIdx=((q.vIdx==null?0:q.vIdx)+1)%pool.length; const v=pool[nextIdx];
        return { ...q, vIdx:nextIdx, title:v.title, target:v.target, kind:v.kind, amt:v.amt, prog:0, claimed:false };
      });
      return { quests };
    });
    setTimeout(()=>this.showToast('\u2728 New quest available \u2014 keep exploring!'), 200);
  }

  // ---------- map / region ----------
  tapRegion(id){ this.setState({ riRegion:id, riOpen:true }); }
  enterRegion(id){ const g=this.creatures[this.regions.find(r=>r.id===id).guide]; this.setState({ currentRegion:id, exploreProgress:0, gotCollectible:false, riOpen:false, inLadder:false, regionStage:0, regionLadder:this.ladderFor(id), screen:'region', avatarLine:this.pick(g.discovery) }); }
  move(){
    const s=this.state; const next=Math.min(100, s.exploreProgress+20);
    let acorns=s.acorns, got=s.gotCollectible;
    if(!got && next>=40){ got=true; acorns+=5; this.showToast('Found a treasure  +5 Acorns'); this.tickQuest('collect'); }
    this.setState({ exploreProgress:next, gotCollectible:got, acorns, avatarLine:this.pick(this.guideOf(s.currentRegion).discovery) });
    if(next>=100){ clearTimeout(this._mv); this._mv=setTimeout(()=>this.startPuzzle(),360); }
  }

  // ---------- puzzles ----------
  startPuzzle(){
    const r=this.region(); this.startRegionStage(0, this.ladderFor(r.id));
  }
  startRegionStage(idx, ladder){
    const r=this.region(); const entry=ladder[idx];
    this.startPuzzleType(entry.t, r.guide, false, { idx, ladder, name:entry.n, tier:entry.d });
  }
  startRegionPuzzle(regionId, type){
    const r=this.regions.find(x=>x.id===regionId);
    this.setState({ currentRegion:regionId, riOpen:false });
    this.startPuzzleType(type, r.guide, false);
  }
  pGuide(){ return this.creatures[this.state.puzzleGuide] || this.guideOf(this.state.currentRegion); }
  startPuzzleType(t, guideId, fromCodex, ladderInfo, eventId){
    const g=this.creatures[guideId] || this.guideOf(this.state.currentRegion);
    const base={ screen:'puzzle', puzzleType:t, puzzleGuide:guideId, puzzleFromCodex:!!fromCodex,
      inLadder:!!ladderInfo, regionStage: ladderInfo?ladderInfo.idx:0, regionLadder: ladderInfo?ladderInfo.ladder:null,
      puzzleDisplayName: ladderInfo?ladderInfo.name:null, puzzleTier: ladderInfo?ladderInfo.tier:null,
      eventTrial: eventId||null,
      hintOpen:false, attempts:0, hintText:this.pick(g.discovery) };
    if(t==='colour') base.cm=this.initColour();
    else if(t==='word') base.word=this.initWord();
    else if(t==='trace') base.trace=this.initTrace();
    else if(t==='odd') base.odd=this.initOdd();
    else if(t==='count') base.count=this.initCount();
    else if(t==='maze') base.maze=this.initMaze();
    else if(t==='memory') base.mem=this.initMemory();
    else if(t==='flow') base.flow=this.initFlow();
    else if(t==='shape') base.shp=this.initShape();
    else if(t==='sequence') base.seq=this.initSequence();
    else if(t==='weight') base.wgt=this.initWeight();
    else if(t==='light') base.lgt=this.initLight();
    else if(t==='shadow') base.shd=this.initShadow();
    else if(t==='rune') base.rune=this.initRune();
    else if(t==='pattern') base.pat=this.initRecall(9,4);
    else if(t==='sound') base.snd=this.initRecall(4,4);
    else if(t==='matrix') base.mtx=this.initRecall(16,5);
    else if(t==='number') base.num=this.initNumber();
    else if(t==='slide') base.slide=this.initSlide();
    else if(t==='hanoi') base.hanoi=this.initHanoi();
    else if(t==='eqn') base.eqn=this.initEqn();
    else if(t==='dots') base.dots=this.initDots();
    this.setState(base);
    if(t==='pattern'){ clearTimeout(this._rw); this._rw=setTimeout(()=>this.recallWatch('pat'),500); }
    if(t==='sound'){ clearTimeout(this._rw); this._rw=setTimeout(()=>this.recallWatch('snd'),500); }
    if(t==='matrix'){ clearTimeout(this._rw); this._rw=setTimeout(()=>this.recallWatch('mtx'),500); }
  }
  fail(){ this.showToast(this.pick(this.pGuide().fail)); this.setState(s=>({attempts:s.attempts+1})); }

  // ---------- word match (spell the picture) ----------
  initWord(){
    const bank=[ {e:'\u2600\ufe0f',w:'SUN'},{e:'\ud83e\udd8a',w:'FOX'},{e:'\ud83d\udc1d',w:'BEE'},{e:'\ud83e\udd89',w:'OWL'},
      {e:'\ud83c\udf43',w:'LEAF'},{e:'\u2b50',w:'STAR'},{e:'\ud83c\udf33',w:'TREE'},{e:'\ud83d\udc38',w:'FROG'},
      {e:'\ud83d\udc1f',w:'FISH'},{e:'\ud83c\udf19',w:'MOON'},{e:'\ud83d\udc26',w:'BIRD'},{e:'\ud83c\udf1f',w:'GLOW'} ];
    const pick=this.pick(bank);
    const letters=this.shuffle(pick.w.split('').map((ch,i)=>({ id:'L'+i, ch })));
    return { emoji:pick.e, word:pick.w, letters, built:[], usedIds:[] };
  }
  wordTap(id){
    const w=this.state.word; if(!w) return;
    if(w.usedIds.includes(id)) return;
    const tile=w.letters.find(x=>x.id===id);
    const need=w.word[w.built.length];
    if(tile && tile.ch===need){
      const nw={ ...w, built:[...w.built, tile.ch], usedIds:[...w.usedIds, id] };
      this.setState({ word:nw });
      if(nw.built.length===nw.word.length){ clearTimeout(this._wd); this._wd=setTimeout(()=>this.solvePuzzle(),450); }
    } else { this.fail(); }
  }

  // ---------- glyph trace (draw to connect) ----------
  initTrace(){
    const shapes=[
      [[50,12],[80,34],[68,74],[32,74],[20,34]],            // pentagon
      [[22,22],[78,22],[78,78],[22,78]],                    // square
      [[50,10],[90,40],[74,86],[26,86],[10,40]],            // 5-point
      [[18,30],[50,12],[82,30],[68,82],[32,82]],            // crown
      [[50,12],[62,40],[90,40],[66,60],[76,88],[50,70],[24,88],[34,60],[10,40],[38,40]] // star (10)
    ];
    const pts=this.pick(shapes);
    const dots=pts.map((p,i)=>({ n:i+1, x:p[0], y:p[1] }));
    return { dots, next:1, path:[], cursor:null, drawing:false };
  }
  traceXY(e){
    const el=this.traceRef && this.traceRef.current; if(!el) return null;
    const r=el.getBoundingClientRect();
    const cx = e.clientX!=null ? e.clientX : (e.touches&&e.touches[0]?e.touches[0].clientX:null);
    const cy = e.clientY!=null ? e.clientY : (e.touches&&e.touches[0]?e.touches[0].clientY:null);
    if(cx==null||cy==null) return null;
    return { x:(cx-r.left)/r.width*100, y:(cy-r.top)/r.height*100 };
  }
  traceDown(e){ const t=this.state.trace; if(!t) return; this.setState({ trace:{...t, drawing:true, path:[], next:1, cursor:null} }, ()=>this.traceMove(e)); }
  traceMove(e){
    const t=this.state.trace; if(!t || !t.drawing) return;
    const p=this.traceXY(e); if(!p) return;
    let { next, path } = t;
    const nd=t.dots.find(d=>d.n===next);
    if(nd && Math.hypot(p.x-nd.x, p.y-nd.y) < 13){ path=[...path, nd.n]; next=next+1; }
    const done = next > t.dots.length;
    this.setState({ trace:{...t, cursor:p, path, next, drawing: done?false:true } });
    if(done){ clearTimeout(this._tr); this._tr=setTimeout(()=>this.solvePuzzle(),450); }
  }
  traceUp(){
    const t=this.state.trace; if(!t) return;
    if(t.next > t.dots.length) return; // already solved
    if(t.path.length){ this.fail(); }
    this.setState({ trace:{...t, drawing:false, path:[], next:1, cursor:null} });
  }

  // ---------- odd one out ----------
  initOdd(){
    const pool=['\ud83c\udf4e','\ud83c\udf4a','\ud83c\udf4b','\ud83c\udf53','\ud83c\udf47','\ud83e\uded0','\ud83c\udf52','\ud83d\udc1d','\ud83d\udc1e','\ud83e\udd8b','\ud83d\udc22','\ud83d\udc38','\u2b50','\ud83c\udf38','\ud83c\udf44','\ud83c\udf40'];
    const sh=this.shuffle(pool); const common=sh[0], odd=sh[1];
    const n=9; const oddIdx=Math.floor(Math.random()*n);
    const cells=Array.from({length:n}).map((_,i)=>({ i, emoji: i===oddIdx?odd:common }));
    return { cells, oddIdx };
  }
  oddTap(i){ const o=this.state.odd; if(!o) return; if(i===o.oddIdx){ clearTimeout(this._od); this._od=setTimeout(()=>this.solvePuzzle(),420); } else this.fail(); }

  // ---------- counting quest ----------
  initCount(){
    const k=4+Math.floor(Math.random()*9);
    const emoji=this.pick(['\ud83c\udf44','\ud83c\udf30','\ud83d\udc1a','\u2b50','\ud83c\udf40','\ud83d\udc1d','\ud83c\udf38','\ud83c\udf41']);
    const opts=new Set([k]); while(opts.size<4){ const d=k+(Math.floor(Math.random()*7)-3); if(d>0&&d<=14) opts.add(d); }
    const items=Array.from({length:k}).map((_,i)=>({ i, x:10+Math.random()*78, y:12+Math.random()*72, rot:(Math.random()*30-15)|0 }));
    return { k, emoji, items, options:this.shuffle([...opts]) };
  }
  countPick(v){ if(v===this.state.count.k){ clearTimeout(this._ct); this._ct=setTimeout(()=>this.solvePuzzle(),420);} else this.fail(); }

  // ---------- maze run ----------
  initMaze(){
    const mazes=[
      { g:[[0,0,0,1,0],[1,1,0,1,0],[0,0,0,0,0],[0,1,1,1,0],[0,0,0,1,0]], s:[0,0], e:[4,4] },
      { g:[[0,1,0,0,0],[0,1,0,1,0],[0,0,0,1,0],[1,1,0,1,0],[0,0,0,0,0]], s:[0,0], e:[4,4] },
      { g:[[0,0,0,0,0],[1,1,1,1,0],[0,0,0,0,0],[0,1,1,1,1],[0,0,0,0,0]], s:[0,0], e:[4,4] },
      { g:[[0,0,1,0,0],[1,0,1,0,1],[1,0,0,0,1],[1,1,1,0,0],[0,0,0,0,1]], s:[0,0], e:[4,3] }
    ];
    const m=this.pick(mazes);
    return { grid:m.g, pos:m.s.slice(), start:m.s, goal:m.e, N:5, trail:[m.s.join(',')] };
  }
  mazeMove(dr,dc){
    const m={...this.state.maze}; if(!m.grid) return;
    const nr=m.pos[0]+dr, nc=m.pos[1]+dc;
    if(nr<0||nc<0||nr>=m.N||nc>=m.N) return;
    if(m.grid[nr][nc]===1){ this.fail(); return; }
    m.pos=[nr,nc]; m.trail=[...m.trail, nr+','+nc]; this.setState({maze:m});
    if(nr===m.goal[0] && nc===m.goal[1]){ clearTimeout(this._mz); this._mz=setTimeout(()=>this.solvePuzzle(),420); }
  }

  // ---------- shape fit ----------
  initShape(){
    const kinds=[{k:'circle',br:'50%',cp:'none'},{k:'square',br:'14%',cp:'none'},{k:'triangle',br:'0',cp:'polygon(50% 0,100% 100%,0 100%)'},{k:'star',br:'0',cp:'polygon(50% 0,61% 35%,98% 35%,68% 57%,79% 91%,50% 70%,21% 91%,32% 57%,2% 35%,39% 35%)'}];
    const slots=this.shuffle(kinds).map((d,i)=>({ id:'sl'+i, k:d.k, cp:d.cp, br:d.br, filled:false }));
    const tray=this.shuffle(kinds.map((d,i)=>({ id:'pc'+i, k:d.k, cp:d.cp, br:d.br, used:false })));
    return { slots, tray, selected:null };
  }
  shapeSelect(id){ const sh={...this.state.shp}; sh.selected = sh.selected===id?null:id; this.setState({shp:sh}); }
  shapeDrop(slotId){
    const sh={...this.state.shp}; if(!sh.selected) return;
    const pc=sh.tray.find(p=>p.id===sh.selected); const sl=sh.slots.find(x=>x.id===slotId);
    if(!pc||!sl||sl.filled) return;
    if(pc.k===sl.k){
      sh.slots=sh.slots.map(x=>x.id===slotId?{...x,filled:true}:x);
      sh.tray=sh.tray.map(p=>p.id===pc.id?{...p,used:true}:p); sh.selected=null;
      this.setState({shp:sh});
      if(sh.slots.every(x=>x.filled)){ clearTimeout(this._sp); this._sp=setTimeout(()=>this.solvePuzzle(),450); }
    } else { sh.selected=null; this.setState({shp:sh}); this.fail(); }
  }

  // ---------- sequence order ----------
  initSequence(){
    const tiles=this.shuffle([1,2,3,4,5].map((n,i)=>({ id:'t'+i, rank:n, size:38+n*9 }))); return { tiles, next:1, done:[] };
  }
  seqTap(rank){
    const sq={...this.state.seq};
    if(rank===sq.next){ sq.done=[...sq.done,rank]; sq.next++; this.setState({seq:sq});
      if(sq.next>5){ clearTimeout(this._sq); this._sq=setTimeout(()=>this.solvePuzzle(),450); }
    } else { sq.done=[]; sq.next=1; this.setState({seq:sq}); this.fail(); }
  }

  // ---------- weight balance ----------
  initWeight(){ const target=6+Math.floor(Math.random()*8); return { target, placed:[] }; }
  weightAdd(v){ const w={...this.state.wgt}; const sum=w.placed.reduce((a,b)=>a+b,0); if(sum+v>w.target+6) return; w.placed=[...w.placed,v]; this.setState({wgt:w}); this.checkWeight(w); }
  weightRemove(i){ const w={...this.state.wgt}; w.placed=w.placed.filter((_,k)=>k!==i); this.setState({wgt:w}); }
  checkWeight(w){ const sum=w.placed.reduce((a,b)=>a+b,0); if(sum===w.target){ clearTimeout(this._wg); this._wg=setTimeout(()=>this.solvePuzzle(),550); } }

  // ---------- light refraction ----------
  initLight(){ const n=3; const mirrors=[]; for(let i=0;i<n;i++){ const target=Math.floor(Math.random()*2)?0:2; let rot; do{ rot=Math.floor(Math.random()*4);}while(rot===target); mirrors.push({rot,target}); } return { mirrors, n }; }
  lightTap(i){ const l={...this.state.lgt}; l.mirrors=l.mirrors.map((m,k)=>k===i?{...m,rot:(m.rot+1)%4}:m); this.setState({lgt:l});
    if(l.mirrors.every(m=>m.rot===m.target)){ clearTimeout(this._lg); this._lg=setTimeout(()=>this.solvePuzzle(),500); } }

  // ---------- shadow match ----------
  initShadow(){ const target=1+Math.floor(Math.random()*3); let rot=0; return { rot, target }; }
  shadowRotate(){ const sd={...this.state.shd}; sd.rot=(sd.rot+1)%4; this.setState({shd:sd});
    if(sd.rot===sd.target){ clearTimeout(this._sh); this._sh=setTimeout(()=>this.solvePuzzle(),500); } }

  // ---------- rune translation ----------
  initRune(){
    const bank=[ {g:'sun',label:'Sun'}, {g:'water',label:'Water'}, {g:'tree',label:'Tree'}, {g:'mountain',label:'Mountain'}, {g:'star',label:'Star'} ];
    const chosen=this.shuffle(bank).slice(0,3);
    const rounds=chosen.map(c=>{ const wrong=this.shuffle(bank.filter(b=>b.g!==c.g)).slice(0,2); const opts=this.shuffle([{label:c.label,correct:true},...wrong.map(w=>({label:w.label,correct:false}))]); return { g:c.g, label:c.label, opts }; });
    return { rounds, round:0 };
  }
  runePick(correct){ const ru={...this.state.rune}; if(correct){ ru.round++; this.setState({rune:ru}); if(ru.round>=ru.rounds.length){ clearTimeout(this._ru); this._ru=setTimeout(()=>this.solvePuzzle(),450);} } else { this.fail(); } }

  // ---------- number sequence (hard) ----------
  initNumber(){
    const rules=[
      ()=>{ const a=2+Math.floor(Math.random()*5), d=2+Math.floor(Math.random()*6); const seq=[a,a+d,a+2*d,a+3*d]; return {seq, ans:a+4*d, why:'add '+d}; },
      ()=>{ const a=1+Math.floor(Math.random()*3), r=2+Math.floor(Math.random()*2); const seq=[a,a*r,a*r*r,a*r*r*r]; return {seq, ans:a*r*r*r*r, why:'×'+r}; },
      ()=>{ let a=1,b=1; const seq=[a,b]; for(let i=0;i<2;i++){ const c=a+b; seq.push(c); a=b; b=c; } return {seq, ans:a+b, why:'Fibonacci'}; },
      ()=>{ const a=2+Math.floor(Math.random()*4); const seq=[a*a,(a+1)*(a+1),(a+2)*(a+2),(a+3)*(a+3)]; return {seq, ans:(a+4)*(a+4), why:'square numbers'}; }
    ];
    const r=this.pick(rules)(); const opts=new Set([r.ans]);
    while(opts.size<4){ const delta=(Math.floor(Math.random()*9)-4)||3; opts.add(r.ans+delta); }
    return { seq:r.seq, ans:r.ans, why:r.why, options:this.shuffle([...opts]) };
  }
  numberPick(v){ if(v===this.state.num.ans){ clearTimeout(this._nm); this._nm=setTimeout(()=>this.solvePuzzle(),450); } else this.fail(); }

  // ---------- sliding tiles (hard) ----------
  initSlide(){
    const N=3; let order=[1,2,3,4,5,6,7,8,0];
    // shuffle with legal moves to guarantee solvable
    let blank=8;
    for(let k=0;k<60;k++){ const nbrs=this.slideNbrs(blank,N); const t=this.pick(nbrs); [order[blank],order[t]]=[order[t],order[blank]]; blank=t; }
    return { N, order, blank };
  }
  slideNbrs(i,N){ const r=Math.floor(i/N), c=i%N; const out=[]; if(r>0)out.push(i-N); if(r<N-1)out.push(i+N); if(c>0)out.push(i-1); if(c<N-1)out.push(i+1); return out; }
  slideTap(i){
    const sl={...this.state.slide}; const N=sl.N;
    if(!this.slideNbrs(sl.blank,N).includes(i)) return;
    const order=sl.order.slice(); [order[sl.blank],order[i]]=[order[i],order[sl.blank]];
    const blank=i; this.setState({slide:{...sl,order,blank}});
    const solved=order.every((v,idx)=> v===(idx+1)%(N*N));
    if(solved){ clearTimeout(this._sl); this._sl=setTimeout(()=>this.solvePuzzle(),450); }
  }

  // ---------- tower of hanoi (hard) ----------
  initHanoi(){ return { pegs:[[3,2,1],[],[]], sel:null, moves:0 }; }
  hanoiTap(p){
    const h={...this.state.hanoi}; h.pegs=h.pegs.map(x=>x.slice());
    if(h.sel===null){ if(h.pegs[p].length) h.sel=p; this.setState({hanoi:h}); return; }
    if(h.sel===p){ h.sel=null; this.setState({hanoi:h}); return; }
    const from=h.pegs[h.sel], to=h.pegs[p];
    const disc=from[from.length-1];
    if(to.length===0 || to[to.length-1]>disc){ to.push(from.pop()); h.moves++; h.sel=null; this.setState({hanoi:h});
      if(h.pegs[2].length===3){ clearTimeout(this._hn); this._hn=setTimeout(()=>this.solvePuzzle(),450); }
    } else { h.sel=null; this.setState({hanoi:h}); this.fail(); }
  }

  // ---------- equation forge (hard) ----------
  initEqn(){
    const a=3+Math.floor(Math.random()*8), b=2+Math.floor(Math.random()*8);
    const ops=[['+',a+b],['\u2212',a-b],['\u00d7',a*b]];
    const correct=this.pick(ops); const target=correct[1];
    const optionVals=new Set([correct[0]]);
    const labels=['+','−','×','÷'];
    while(optionVals.size<3){ optionVals.add(this.pick(labels)); }
    return { a, b, target, correctOp:correct[0], options:this.shuffle([...optionVals]) };
  }
  eqnPick(op){
    const e=this.state.eqn; let v;
    if(op==='+')v=e.a+e.b; else if(op==='−')v=e.a-e.b; else if(op==='×')v=e.a*e.b; else v=e.a/e.b;
    if(v===e.target){ clearTimeout(this._eq); this._eq=setTimeout(()=>this.solvePuzzle(),450); } else this.fail();
  }

  // ---------- connecting dots (constellation) ----------
  initDots(){
    const shapes=[
      [[50,8],[20,30],[80,30],[32,62],[68,62],[50,90]],
      [[15,20],[50,12],[85,22],[70,52],[82,84],[30,80],[18,52]],
      [[50,10],[78,32],[68,68],[32,68],[22,32],[50,46]],
      [[20,18],[78,16],[60,44],[84,72],[40,66],[14,82]]
    ];
    const pts=this.pick(shapes);
    const dots=pts.map((p,i)=>({ n:i+1, x:p[0], y:p[1] }));
    return { dots, next:1, path:[] };
  }
  dotsTap(n){
    const d={...this.state.dots};
    if(n===d.next){ d.path=[...d.path, n]; d.next++; this.setState({dots:d});
      if(d.next>d.dots.length){ clearTimeout(this._dt); this._dt=setTimeout(()=>this.solvePuzzle(),500); }
    } else { d.path=[]; d.next=1; this.setState({dots:d}); this.fail(); }
  }

  // ---------- recall (pattern / sound / matrix) ----------
  initRecall(n, len){ const seq=[]; for(let i=0;i<len;i++) seq.push(Math.floor(Math.random()*n)); return { n, seq, input:[], phase:'watch', flash:-1 }; }
  recallWatch(field){
    const st={...this.state[field]}; st.phase='watch'; st.input=[]; st.flash=-1; this.setState({[field]:st});
    st.seq.forEach((cell,i)=>{
      setTimeout(()=>{ this.setState(s=>({[field]:{...s[field],flash:cell}})); if(field==='snd') this.playTone(cell); },500+i*620);
      setTimeout(()=>{ this.setState(s=>({[field]:{...s[field],flash:-1}})); },500+i*620+360);
    });
    setTimeout(()=>{ this.setState(s=>({[field]:{...s[field],phase:'input'}})); },500+st.seq.length*620+200);
  }
  recallTap(field, idx){
    const st={...this.state[field]}; if(st.phase!=='input') return;
    if(field==='snd') this.playTone(idx);
    const pos=st.input.length;
    if(idx===st.seq[pos]){ st.input=[...st.input,idx]; this.setState({[field]:st});
      if(st.input.length===st.seq.length){ clearTimeout(this._rc); this._rc=setTimeout(()=>this.solvePuzzle(),450); }
    } else { st.input=[]; st.phase='watch'; this.setState({[field]:st}); this.fail(); clearTimeout(this._rc2); this._rc2=setTimeout(()=>this.recallWatch(field),700); }
  }
  playTone(i){
    // React Native: audio handled by services/audio.ts via onRecallTone callback
    if (typeof this.__onRecallTone === 'function') this.__onRecallTone(i);
  }

  initColour(){
    const defs=[ {key:'sun',color:'#F2B33D',colorDark:'#cf942a',glow:'#FFE7A8',label:'Sun Gold'},
                 {key:'sky',color:'#4F91C9',colorDark:'#3a72a8',glow:'#A8D8EA',label:'Sky Blue'},
                 {key:'rose',color:'#E87FA0',colorDark:'#c45f80',glow:'#FFD4E0',label:'Blossom'} ];
    let items=[]; defs.forEach(d=>{ for(let i=0;i<2;i++) items.push({ id:d.key+i, key:d.key, color:d.color, glow:d.glow, placed:false }); });
    items=this.shuffle(items);
    return { defs, items, selected:null };
  }
  selectItem(id){ const cm={...this.state.cm}; cm.selected = cm.selected===id?null:id; this.setState({cm}); }
  placeBucket(key){
    const cm={...this.state.cm};
    if(!cm.selected){ return; }
    const it=cm.items.find(i=>i.id===cm.selected);
    if(!it){ return; }
    if(it.key===key){
      cm.items=cm.items.map(i=>i.id===it.id?{...i,placed:true}:i); cm.selected=null;
      this.setState({cm});
      if(cm.items.every(i=>i.placed)){ clearTimeout(this._cm); this._cm=setTimeout(()=>this.solvePuzzle(),450); }
    } else {
      cm.selected=null; this.setState({ cm }); this.fail();
    }
  }
  initMemory(){
    const cols=['#E8654E','#4FB8CE','#F2B33D','#8E6FC9','#6FB36A','#E89BB0'];
    let cards=[]; cols.forEach((c,i)=>{ for(let k=0;k<2;k++) cards.push({ id:'c'+i+'-'+k, pk:i, color:c, flipped:false, matched:false }); });
    cards=this.shuffle(cards);
    return { cards, firstId:null, lock:false, moves:0 };
  }
  flipCard(id){
    const m={...this.state.mem}; if(m.lock) return;
    const card=m.cards.find(c=>c.id===id); if(!card||card.flipped||card.matched) return;
    m.cards=m.cards.map(c=>c.id===id?{...c,flipped:true}:c);
    if(m.firstId==null){ m.firstId=id; this.setState({mem:m}); return; }
    m.moves++; const first=m.cards.find(c=>c.id===m.firstId);
    if(first.pk===card.pk){
      m.cards=m.cards.map(c=>(c.id===id||c.id===m.firstId)?{...c,matched:true}:c);
      const done=m.cards.every(c=>c.matched); m.firstId=null; this.setState({mem:m});
      if(done){ clearTimeout(this._mm); this._mm=setTimeout(()=>this.solvePuzzle(),550); }
    } else {
      m.lock=true; const fid=m.firstId; m.firstId=null; this.setState({ mem:m }); this.fail();
      clearTimeout(this._mm2); this._mm2=setTimeout(()=>{
        const mm={...this.state.mem}; mm.cards=mm.cards.map(c=>(c.id===id||c.id===fid)?{...c,flipped:false}:c); mm.lock=false; this.setState({mem:mm});
      },800);
    }
  }
  // ---------- flow direction ----------
  rotCW(sides){ const m={N:'E',E:'S',S:'W',W:'N'}; return sides.map(x=>m[x]); }
  initFlow(){
    const sol=[
      [['W','S'], null,       ['S','E']],
      [['N','S'], null,       ['N','S']],
      [['N','E'], ['W','E'],  ['W','N']]
    ];
    const cells=sol.map((row)=>row.map((sides)=>{
      if(!sides) return { type:'empty' };
      let sd=sides.slice(); const turns=1+Math.floor(Math.random()*3);
      for(let t=0;t<turns;t++) sd=this.rotCW(sd);
      return { type:'pipe', sides:sd };
    }));
    return { cells, R:3, C:3, src:{r:0,c:0}, dst:{r:0,c:2} };
  }
  flowFilled(f){
    const opp={N:'S',S:'N',E:'W',W:'E'}, dR={N:-1,S:1,E:0,W:0}, dC={N:0,S:0,E:1,W:-1};
    const filled={}, key=(r,c)=>r+','+c;
    const sc=f.cells[f.src.r][f.src.c];
    if(!sc||sc.type!=='pipe'||!sc.sides.includes('W')) return filled;
    const stack=[f.src]; filled[key(f.src.r,f.src.c)]=true;
    while(stack.length){
      const cur=stack.pop(); const cell=f.cells[cur.r][cur.c];
      cell.sides.forEach(side=>{
        const nr=cur.r+dR[side], nc=cur.c+dC[side];
        if(nr<0||nc<0||nr>=f.R||nc>=f.C) return;
        const nx=f.cells[nr][nc];
        if(!nx||nx.type!=='pipe'||!nx.sides.includes(opp[side])||filled[key(nr,nc)]) return;
        filled[key(nr,nc)]=true; stack.push({r:nr,c:nc});
      });
    }
    return filled;
  }
  flowSolved(f){ const fl=this.flowFilled(f); const d=f.dst; const dc=f.cells[d.r][d.c]; return !!fl[d.r+','+d.c] && dc && dc.sides.includes('E'); }
  rotateCell(r,c){
    const f={...this.state.flow}; f.cells=f.cells.map(row=>row.slice());
    const cell=f.cells[r][c]; if(!cell||cell.type!=='pipe') return;
    f.cells[r][c]={ ...cell, sides:this.rotCW(cell.sides) };
    this.setState({ flow:f });
    if(this.flowSolved(f)){ clearTimeout(this._fl); this._fl=setTimeout(()=>this.solvePuzzle(),500); }
  }
  flowSeg(side,col){
    const o={ col, left:'auto', top:'auto', right:'auto', bottom:'auto', w:'15px', h:'15px', tf:'none' };
    if(side==='N'){ o.left='50%'; o.top='0'; o.h='56%'; o.tf='translateX(-50%)'; }
    if(side==='S'){ o.left='50%'; o.bottom='0'; o.h='56%'; o.tf='translateX(-50%)'; }
    if(side==='E'){ o.top='50%'; o.right='0'; o.w='56%'; o.tf='translateY(-50%)'; }
    if(side==='W'){ o.top='50%'; o.left='0'; o.w='56%'; o.tf='translateY(-50%)'; }
    return o;
  }

  toggleHint(){ this.setState({ hintOpen:!this.state.hintOpen }); }
  rankForXp(xp){ let r=this.ranks[0]; for(const rk of this.ranks){ if(xp>=rk.xp) r=rk; } return r; }
  nextRank(xp){ return this.ranks.find(rk=>rk.xp>xp) || null; }
  solvePuzzle(){
    const fromCodex=this.state.puzzleFromCodex;
    const inLadder=this.state.inLadder;
    const eventId=this.state.eventTrial;
    const trial=eventId?this.eventTrialDefs.find(x=>x.id===eventId):null;
    const ladder=this.state.regionLadder||[];
    const stage=this.state.regionStage||0;
    const isLast = inLadder && stage>=ladder.length-1;
    const ladderMore = inLadder && !isLast;
    const small = fromCodex || !!eventId;
    const gid=this.state.puzzleGuide || this.region().guide; const c=this.creatures[gid];
    const ag=small?18:35, gg=small?2:4, bg=small?3:8, xg=small?60:120;
    const r=this.region();
    const isFinale = isLast && r.id==='stardust';
    const rwTitle = eventId ? 'Storm Trial Cleared!' : (ladderMore ? 'Challenge Cleared!' : (isLast ? 'Region Cleared!' : 'Puzzle Solved!'));
    this.setState(s=>{
      const oldRank=this.rankForXp(s.xp).num; const newXp=s.xp+xg; const newRank=this.rankForXp(newXp).num;
      const rankedUp=newRank>oldRank;
      if(rankedUp){ const rn=this.rankForXp(newXp); clearTimeout(this._rt); this._rt=setTimeout(()=>this.showToast('\u2728 Explorer Rank '+rn.num+' \u2014 '+rn.name+'!'),650); }
      return {
        acorns:s.acorns+ag, glowDust:s.glowDust+gg, xp:newXp, rank:newRank, puzzlesSolved:(s.puzzlesSolved||0)+1,
        skills:{...s.skills, [this.skillOf(this.state.puzzleType)]:(s.skills[this.skillOf(this.state.puzzleType)]||0)+1},
        rainPearls: eventId ? s.rainPearls+trial.pearls : s.rainPearls,
        eventDone: eventId ? {...s.eventDone, [eventId]:true} : s.eventDone,
        bonds:{...s.bonds, [gid]:Math.min(100,(s.bonds[gid]||0)+bg)},
        rw:{ title:rwTitle, acorns:ag, glowDust:gg, bond:bg, xp:xg, creature:c.name, body:c.body, glow:c.glow, line:this.pick(c.solve),
             rankedUp, newRankName:rankedUp?this.rankForXp(newXp).name:'', newRankNum:newRank,
             isEvent:!!eventId, pearls: eventId?trial.pearls:0,
             ladderMore, ladderProg: inLadder ? ('Puzzle '+(stage+1)+' of '+ladder.length+(isLast?'  \u00b7  region cleared!':' cleared')) : '',
             hasUnlock:false, unlockedName:'', unlockedGuide:'' }
      };
    }, ()=>{ if(isFinale){ this.tickQuest('solve'); this.playFinale(); } else { this.setState({screen:'reward'}); } });
  }
  solveDemo(){ this.solvePuzzle(); }
  rewardContinue(){
    const s=this.state;
    this.tickQuest('solve');
    if(s.eventTrial){ this.setState({eventTrial:null}); this.go('event'); return; }
    if(s.inLadder){
      const len=s.regionLadder?s.regionLadder.length:1;
      if((s.regionStage||0) < len-1){ this.startRegionStage((s.regionStage||0)+1, s.regionLadder); return; }
      if(this.region().id!=='stardust'){ this.startBoss(this.region().id); return; }
    }
    this.go(s.puzzleFromCodex ? 'journey' : 'map');
  }

  // ---------- seasonal event ----------
  openEvent(){ this.setState({ screen:'event', riOpen:false }); }
  startEventTrial(id){ const tr=this.eventTrialDefs.find(x=>x.id===id); if(!tr) return; this.startPuzzleType(tr.type, tr.guide, false, null, id); }
  buyEvent(id){
    const it=this.eventShopDefs.find(x=>x.id===id); if(!it) return;
    if(this.state.eventOwned[id]) return;
    if(this.state.rainPearls < it.cost){ this.showToast('Need '+(it.cost-this.state.rainPearls)+' more Rain Pearls'); return; }
    this.setState(s=>({ rainPearls:s.rainPearls-it.cost, eventOwned:{...s.eventOwned,[id]:true} }));
    this.showToast(it.name+' unlocked! \u2728');
  }

  // ---------- daily chest + parent dashboard ----------
  begin(){ this.setState({ screen:'map', dailyOpen: !this.state.dailyShown }); }
  openDaily(){ this.setState({ dailyOpen:true }); }
  closeDaily(){ this.setState({ dailyOpen:false, dailyShown:true }); }
  claimDaily(){
    if(this.state.dailyClaimed) return;
    const r=this.dailyRewards[0];
    this.setState(s=>{ const p={ dailyClaimed:1 }; if(r.kind==='acorns')p.acorns=s.acorns+r.amt; else p.glowDust=s.glowDust+r.amt; return p; });
    this.showToast('Day 1 gift claimed \u2014 '+r.label+' \u2728');
  }
  openParent(){ this.setState({ screen:'parent', riOpen:false }); }

  // ---------- boss battle ----------
  startBoss(regionId){ const r=this.regions.find(x=>x.id===regionId); this.setState({ screen:'boss', inLadder:false, boss:this.makeBossRound(r, 3) }); }
  makeBossRound(r, hp){
    const syms=['\u25c6','\u25b2','\u25cf','\u2605','\u2726','\u2b22','\u271a','\u2756'];
    const sh=this.shuffle(syms);
    const options=this.shuffle([sh[0],sh[1],sh[2]]);
    return { regionId:r.id, name:r.boss, body:r.primary, glow:r.glow, secondary:r.secondary, hp, maxHp:3, round:4-hp, target:sh[0], options, defeated:false, flash:false };
  }
  bossStrike(sym){
    const b=this.state.boss; if(!b||b.defeated) return;
    if(sym===b.target){
      const hp=b.hp-1;
      if(hp<=0){ this.setState({ boss:{...b, hp:0, defeated:true, flash:true} }); clearTimeout(this._bz); this._bz=setTimeout(()=>this.bossDefeated(),1000); }
      else { const r=this.regions.find(x=>x.id===b.regionId); const nr=this.makeBossRound(r, hp); nr.flash=true; this.setState({boss:nr}); this.showToast('Direct hit!  '+hp+' to go'); clearTimeout(this._bf); this._bf=setTimeout(()=>this.setState(s=>({boss:s.boss?{...s.boss,flash:false}:s.boss})),300); }
    } else { this.fail(); }
  }
  bossDefeated(){
    const b=this.state.boss; const r=this.regions.find(x=>x.id===b.regionId);
    const next=this.regions.find(x=>x.num===r.num+1);
    const willUnlock = next && !this.state.unlocked[next.id];
    this.setState(s=>({
      acorns:s.acorns+100, glowDust:s.glowDust+8, xp:s.xp+150, rank:this.rankForXp(s.xp+150).num, puzzlesSolved:(s.puzzlesSolved||0)+1,
      unlocked: willUnlock ? {...s.unlocked,[next.id]:true} : s.unlocked,
      rw:{ title:'Boss Defeated!', acorns:100, glowDust:8, bond:0, xp:150, creature:r.boss, body:r.primary, glow:r.glow,
           line:r.boss+' is calmed at last. The forest breathes again.',
           rankedUp:false, newRankName:'', newRankNum:s.rank, isBoss:true, isEvent:false, pearls:0, ladderMore:false, ladderProg:'',
           hasUnlock:!!willUnlock, unlockedName: willUnlock?next.name:'', unlockedGuide: willUnlock?this.creatures[next.guide].name:'' },
      screen:'reward'
    }));
  }

  // ---------- finale cinematic ----------
  playFinale(){
    this.setState({ screen:'finale', finaleStage:0 });
    this._fin=[];
    [700,2400,4300,6300,8200].forEach((t,i)=>{ this._fin.push(setTimeout(()=>this.setState({finaleStage:i+1}), t)); });
  }
  finaleSkip(){ (this._fin||[]).forEach(clearTimeout); this.setState({finaleStage:5}); }
  finaleDone(){ (this._fin||[]).forEach(clearTimeout); this.setState(s=>({ screen:'journey', finaleSeen:true })); }

  // ---------- creatures ----------
  openDetail(id){ this.setState({ detailId:id, screen:'detail' }); }
  addBond(){
    const id=this.state.detailId; const old=this.state.bonds[id]||0; const nw=Math.min(100, old+5);
    this.setState({ bonds:{...this.state.bonds, [id]:nw} });
    const ms=[10,20,30,40,50,60,70,80,90,100].find(m=>old<m && nw>=m);
    if(ms) this.showToast(this.creatures[id].name+' \u2014 Bond '+ms+' reached! \u2728');
    else this.showToast('+5 Bond with '+this.creatures[id].name);
    this.tickQuest('bond');
  }

  // ---------- sanctuary ----------
  collectGift(id){
    if(!this.state.gifts[id]) return;
    this.setState(s=>({ gifts:{...s.gifts, [id]:false}, acorns:s.acorns+15, glowDust:s.glowDust+2, bonds:{...s.bonds,[id]:Math.min(100,(s.bonds[id]||0)+3)} }));
    this.showToast(this.creatures[id].name+'\u2019s gift  +15 Acorns +3 Bond');
  }

  // ---------- render ----------
  renderVals(){
    const s=this.state; const scr=s.screen;
    const cr=this.region(); const gc=this.creatures[cr.guide];
    const hub = (scr==='map'||scr==='creatures'||scr==='sanctuary'||scr==='journey');
    const onSceneDark = (scr==='region' && cr.dark);
    const statusColor = (scr==='puzzle'||scr==='reward'||scr==='detail'||scr==='finale'||scr==='event'||scr==='boss'||onSceneDark) ? '#FFF3E2'
      : (onSceneDark) ? '#fff' : '#3A2A1C';

    // fireflies (title) + sparks (reward) + embers (sanctuary)
    const fireflies = [ {x:22,y:60,dur:5,delay:0},{x:70,y:48,dur:6.4,delay:.6},{x:42,y:70,dur:5.6,delay:1.2},{x:84,y:64,dur:6,delay:.3},{x:14,y:74,dur:5.2,delay:1.6},{x:60,y:80,dur:6.8,delay:.9},{x:34,y:54,dur:5.9,delay:2} ];
    const rewardSparks = [ {x:18,y:30,dur:1.6,delay:0},{x:80,y:26,dur:1.9,delay:.3},{x:30,y:64,dur:1.7,delay:.6},{x:72,y:66,dur:2,delay:.2},{x:50,y:20,dur:1.5,delay:.8},{x:12,y:50,dur:1.8,delay:.5},{x:88,y:52,dur:1.6,delay:1},{x:46,y:74,dur:1.9,delay:.4} ];
    const embers = [ {x:20,dur:1.8,delay:0},{x:45,dur:2.2,delay:.5},{x:65,dur:1.6,delay:1},{x:35,dur:2,delay:1.4} ];

    // map nodes
    const mapNodes = this.regions.map(r=>{ const open=!!s.unlocked[r.id]; return {
      id:r.id, num:r.num, name:r.name, x:r.x, y:r.y, color:r.primary, glow:r.glow,
      locked:!open, nodeOpacity: open?1:0.62,
      onTap:()=>this.tapRegion(r.id)
    }; });
    const mapPoints = this.regions.map(r=>r.x+','+r.y).join(' ');
    const regionsOpen = Object.values(s.unlocked).filter(Boolean).length;

    // region info sheet
    let ri=null;
    if(s.riRegion){
      const r=this.regions.find(x=>x.id===s.riRegion); const g=this.creatures[r.guide]; const open=!!s.unlocked[r.id];
      const rLadder=this.ladderFor(r.id);
      const tierCount=(d)=>rLadder.filter(e=>e.d===d).length;
      ri={ name:r.name, guideName:g.name, difficulty:r.difficulty, locked:!open, unlock:r.unlock,
        desc:r.desc, biome:r.biome, puzzleName:r.puzzleName, boss:r.boss, collectibles:r.collectibles,
        primary:r.primary, glow:r.glow, puzzleCount:rLadder.length,
        challengeHeader: rLadder.length+'-Puzzle Journey \u00b7 '+tierCount('E')+' Easy \u00b7 '+tierCount('M')+' Medium \u00b7 '+tierCount('H')+' Hard',
        challenges:rLadder.map(e=>{ const pc=this.puzzleCodexList.find(p=>p.type===e.t)||{color:r.primary,colorDark:r.groundDark}; const tm=this.tierMeta(e.d);
          return { type:e.t, name:e.n, color:pc.color, colorDark:pc.colorDark, tierLabel:tm.l, tierColor:tm.c, tierBg:tm.bg, locked:!open, op:open?'1':'.6', cursor:open?'pointer':'default', onPlay: open?(()=>this.startRegionPuzzle(r.id, e.t)):(()=>this.showToast('Unlock this region first')) }; }),
        btnLabel: open?('Enter Region \u00b7 '+rLadder.length+' puzzles'):'Preview Region',
        btnA: open?'#5EA862':'#8b7fb0', btnB: open?'#3f7d47':'#6a5e96', btnShadow: open?'#2f5e36':'#4f4677',
        onEnter:()=>this.enterRegion(r.id) };
    }

    // exploration scene
    const ep=s.exploreProgress;
    const farX=ep*1.4, midX=ep*3.0, nearX=ep*5.0;
    const markerLeft = 50 + (100-ep)*0.22;
    const showCollectible = !s.gotCollectible && scr==='region';
    const avatarLine = s.avatarLine || gc.discovery[0];
    const moveLabel = ep>=80 ? 'Approach' : (ep>=40 ? 'Keep going' : 'Explore');

    // puzzle
    const isLadderPuzzle = scr==='puzzle' && !!s.inLadder;
    const ladderArr = s.regionLadder||[];
    const ladderLabel = isLadderPuzzle ? ('Puzzle '+((s.regionStage||0)+1)+' / '+ladderArr.length) : '';
    const tierObj = (isLadderPuzzle && s.puzzleTier) ? this.tierMeta(s.puzzleTier) : null;
    const showPuzzleTier = !!tierObj; const puzzleTierLabel = tierObj?tierObj.l:''; const puzzleTierColor = tierObj?tierObj.c:'#999';
    const markerPuzzleName = (this.ladderFor(cr.id)[0]||{}).n || cr.puzzleName;
    const rewardBtnLabel = (s.rw && s.rw.ladderMore) ? 'Next Puzzle \u2192' : 'Continue';
    const rwHasProg = !!(s.rw && s.rw.ladderProg);
    const isColour = scr==='puzzle' && s.puzzleType==='colour';
    const isMemory = scr==='puzzle' && s.puzzleType==='memory';
    const isFlow = scr==='puzzle' && s.puzzleType==='flow';
    const pt=s.puzzleType;
    const pg = this.creatures[s.puzzleGuide] || gc;
    const pcMeta = this.puzzleCodexList.find(p=>p.type===pt) || {name:cr.puzzleName, skill:''};
    const puzzleTitle = scr==='puzzle' ? ((isLadderPuzzle && s.puzzleDisplayName) ? s.puzzleDisplayName : pcMeta.name) : cr.puzzleName;
    const isWord=scr==='puzzle'&&pt==='word', isTrace=scr==='puzzle'&&pt==='trace', isOdd=scr==='puzzle'&&pt==='odd', isCount=scr==='puzzle'&&pt==='count', isMaze=scr==='puzzle'&&pt==='maze';
    const isShape=scr==='puzzle'&&pt==='shape', isSequence=scr==='puzzle'&&pt==='sequence', isWeight=scr==='puzzle'&&pt==='weight',
          isLight=scr==='puzzle'&&pt==='light', isShadow=scr==='puzzle'&&pt==='shadow', isRune=scr==='puzzle'&&pt==='rune',
          isPattern=scr==='puzzle'&&pt==='pattern', isSound=scr==='puzzle'&&pt==='sound', isMatrix=scr==='puzzle'&&pt==='matrix',
          isNumber=scr==='puzzle'&&pt==='number', isSlide=scr==='puzzle'&&pt==='slide', isHanoi=scr==='puzzle'&&pt==='hanoi', isEqn=scr==='puzzle'&&pt==='eqn', isDots=scr==='puzzle'&&pt==='dots';
    const isDemo = false;
    let cmBuckets=[], cmTray=[], cmEmpty=false, memCards=[], memMoves=0, demoName='', demoDesc='', demoSkill='', flowCells=[];
    let dotsList=[], dotsLine='', dotsLabel='';
    let shapeSlots=[], shapeTray=[], seqTiles=[], seqHint='', wgtWeights=[], wgtPlaced=[], wgtSum=0, wgtTarget=0,
        lightMirrors=[], lightDone=false, shadowTarget=[], shadowCur=[], shadowSolved=false, runeGlyph='', runeOpts=[], runeProgress='',
        recallPads=[], recallPhase='', recallLabel='', recallField='',
        numSeq=[], numOptions=[], slideTiles=[], hanoiPegs=[], eqnA=0, eqnB=0, eqnTarget=0, eqnOptions=[];
    if(isColour && s.cm){
      cmBuckets = s.cm.defs.map(d=>({ label:d.label, color:d.color, colorDark:d.colorDark, count:s.cm.items.filter(i=>i.placed&&i.key===d.key).length, onTap:()=>this.placeBucket(d.key) }));
      cmTray = s.cm.items.filter(i=>!i.placed).map(i=>({ id:i.id, color:i.color, glow:i.glow, selected:s.cm.selected===i.id, scale:s.cm.selected===i.id?'1.18':'1', ring:s.cm.selected===i.id?'3px solid #FFF3C4':'none', onTap:()=>this.selectItem(i.id) }));
      cmEmpty = s.cm.items.every(i=>i.placed);
    }
    if(isMemory && s.mem){
      memMoves=s.mem.moves;
      memCards = s.mem.cards.map(c=>{ const show=c.flipped||c.matched; return { id:c.id, face: show?'#fff8ef':'linear-gradient(160deg,#5a8a63,#3f6f47)', dot: show?c.color:'transparent', op: c.matched?'.45':'1', onTap:()=>this.flipCard(c.id) }; });
    }
    if(isFlow && s.flow){
      const f=s.flow; const filled=this.flowFilled(f);
      for(let r=0;r<f.R;r++){ for(let c=0;c<f.C;c++){
        const cell=f.cells[r][c];
        if(!cell || cell.type==='empty'){ flowCells.push({ key:r+'-'+c, hub:'transparent', cellBg:'rgba(255,255,255,.04)', cellShadow:'none', segs:[], onTap:()=>{} }); continue; }
        const fill=!!filled[r+','+c]; const col= fill ? '#54C7E0' : '#8ea6b6';
        const segs=cell.sides.map(side=>this.flowSeg(side,col));
        flowCells.push({ key:r+'-'+c, hub:col, cellBg: fill?'rgba(84,199,224,.12)':'rgba(255,248,239,.07)', cellShadow:'inset 0 0 0 2px rgba(255,255,255,.12)', segs, onTap:()=>this.rotateCell(r,c) });
      } }
    }
    if(isShape && s.shp){
      shapeSlots=s.shp.slots.map(sl=>({ id:sl.id, cp:sl.cp, br:sl.br, filled:sl.filled, holeDisp: sl.filled?'none':'block', onTap:()=>this.shapeDrop(sl.id) }));
      shapeTray=s.shp.tray.filter(p=>!p.used).map(p=>({ id:p.id, cp:p.cp, br:p.br, sel:s.shp.selected===p.id, scale:s.shp.selected===p.id?'1.16':'1', onTap:()=>this.shapeSelect(p.id) }));
    }
    if(isSequence && s.seq){
      seqTiles=s.seq.tiles.map(t=>{ const done=s.seq.done.includes(t.rank); const isNext=s.seq.next===t.rank;
        return { id:t.id, rank:t.rank, size:t.size, op: done?'.4':'1', scale: isNext?'scale(1.06)':'scale(1)',
          leafGlow:'#bfe89a', leafBody:'#6FB36A', shadow: done?'inset 0 0 0 3px rgba(255,255,255,.5)':'0 6px 14px -4px rgba(0,0,0,.4)', onTap:()=>this.seqTap(t.rank) }; });
      seqHint='Tap the leaves from smallest to largest.';
    }
    if(isWeight && s.wgt){
      wgtTarget=s.wgt.target; wgtSum=s.wgt.placed.reduce((a,b)=>a+b,0);
      wgtWeights=[1,2,3,5].map(v=>({ v, onTap:()=>this.weightAdd(v) }));
      wgtPlaced=s.wgt.placed.map((v,i)=>({ v, onTap:()=>this.weightRemove(i) }));
    }
    const wgtTilt = isWeight ? Math.max(-14, Math.min(14, (wgtSum-wgtTarget)*2.2)) : 0;
    if(isLight && s.lgt){
      lightMirrors=s.lgt.mirrors.map((m,i)=>({ i, deg:m.rot*90, ok:m.rot===m.target,
        bg: m.rot===m.target ? 'rgba(224,64,251,.28)' : 'rgba(255,248,239,.1)',
        glow: m.rot===m.target ? '0 0 18px 4px rgba(224,64,251,.6), inset 0 0 0 2px rgba(224,64,251,.7)' : 'inset 0 0 0 2px rgba(255,255,255,.2)',
        onTap:()=>this.lightTap(i) }));
      lightDone=s.lgt.mirrors.every(m=>m.rot===m.target);
    }
    const lightGem = lightDone ? '#9BE86A' : '#3a5a30';
    const lightGemGlow = lightDone ? '0 0 20px 6px rgba(155,232,106,.8)' : 'none';
    const lightHintOp = lightDone ? '0' : '.8';
    let shadowTargetDeg=0, shadowCurDeg=0;
    if(isShadow && s.shd){ shadowSolved=s.shd.rot===s.shd.target; shadowCurDeg=s.shd.rot*90; shadowTargetDeg=s.shd.target*90; }
    let runeSymbol='';
    if(isRune && s.rune){
      const rd=s.rune.rounds[s.rune.round];
      const glyphs={sun:'\u2600\ufe0f',water:'\u3030\ufe0f',tree:'\u2191',mountain:'\u25b2',star:'\u2736'};
      if(rd){ runeSymbol=glyphs[rd.g]||'\u2756'; runeOpts=rd.opts.map(o=>({ label:o.label, onTap:()=>this.runePick(o.correct) })); runeProgress=(s.rune.round+1)+' / '+s.rune.rounds.length; }
    }
    const isRecall = isPattern || isSound || isMatrix;
    let recallIntro='', recallCols='repeat(3,1fr)', recallSize='62px', recallRadius='16px';
    if(isRecall){
      recallField=isPattern?'pat':(isSound?'snd':'mtx'); const st=s[recallField];
      if(st){
        recallPhase=st.phase;
        const cols=['#E8654E','#4FB8CE','#F2B33D','#6FB36A','#8E6FC9','#E89BB0','#5DADE2','#E8822F','#9B59B6','#3DBE9B','#D96459','#7E6BC9','#56A0D3','#C97FB0','#86C166','#E0A93B'];
        recallPads=Array.from({length:st.n}).map((_,i)=>{ const lit=st.flash===i;
          return { i, bg:'radial-gradient(circle at 38% 30%,'+cols[i%cols.length]+','+cols[i%cols.length]+')',
            shadow: lit ? '0 0 22px 6px '+cols[i%cols.length]+', inset 0 0 0 3px #fff' : '0 6px 14px -4px rgba(0,0,0,.45)',
            scale: lit ? 'scale(1.08)' : 'scale(1)', filter: lit ? 'brightness(1.5)' : (st.phase==='watch'?'brightness(.78)':'brightness(1)'),
            onTap:()=>this.recallTap(recallField,i) }; });
        recallLabel = st.phase==='watch' ? 'Watch closely\u2026' : ('Your turn \u2014 '+st.input.length+' / '+st.seq.length);
        if(isPattern){ recallCols='repeat(3,1fr)'; recallSize='58px'; recallRadius='14px'; recallIntro='Memorise the glowing path, then tap it back in the same order.'; }
        else if(isSound){ recallCols='repeat(2,1fr)'; recallSize='76px'; recallRadius='20px'; recallIntro='Listen to the melody, then tap the pads to play it back.'; }
        else { recallCols='repeat(4,1fr)'; recallSize='52px'; recallRadius='12px'; recallIntro='A 4\u00d74 grid lights up in sequence. Repeat the full pattern from memory.'; }
      }
    }
    if(isNumber && s.num){ numSeq=s.num.seq.map(n=>({v:n})); numOptions=s.num.options.map(v=>({v, onTap:()=>this.numberPick(v)})); }
    if(isSlide && s.slide){ const N=s.slide.N; slideTiles=s.slide.order.map((v,i)=>{ const goal=v===(i+1)%(N*N); const blank=v===0;
      return { i, v, label: blank?'':String(v), blank, goal,
        bg: blank?'transparent':(goal?'linear-gradient(180deg,#5EA862,#3f7d47)':'linear-gradient(180deg,#C0392B,#922b21)'),
        shadow: blank?'inset 0 0 0 2px rgba(255,255,255,.1)':'0 5px 12px -4px rgba(0,0,0,.5)', cursor: blank?'default':'pointer',
        onTap:()=>this.slideTap(i) }; }); }
    if(isHanoi && s.hanoi){ const dW={1:34,2:54,3:74}; const dC={1:'#E8A24E',2:'#D9694F',3:'#7E6BC9'};
      hanoiPegs=s.hanoi.pegs.map((peg,pi)=>({ pi, sel:s.hanoi.sel===pi,
        bg: s.hanoi.sel===pi?'rgba(124,107,201,.22)':'rgba(255,255,255,.06)',
        ring: s.hanoi.sel===pi?'inset 0 0 0 2px rgba(124,107,201,.7)':'inset 0 0 0 1px rgba(255,255,255,.12)',
        discs:peg.map(d=>({ d, w:dW[d], color:dC[d] })), onTap:()=>this.hanoiTap(pi) })); }
    if(isEqn && s.eqn){ eqnA=s.eqn.a; eqnB=s.eqn.b; eqnTarget=s.eqn.target; eqnOptions=s.eqn.options.map(op=>({ op, onTap:()=>this.eqnPick(op) })); }
    if(isDots && s.dots){
      const D=s.dots; dotsLabel='Connect '+D.next+' of '+D.dots.length;
      dotsList=D.dots.map(dt=>({ n:dt.n, x:dt.x, y:dt.y, done:D.path.includes(dt.n), isNext:dt.n===D.next,
        bg: D.path.includes(dt.n)?'#FFD86B':(dt.n===D.next?'#9FB8FF':'rgba(255,255,255,.85)'),
        ring: dt.n===D.next?'0 0 0 4px rgba(159,184,255,.45), 0 0 16px 4px rgba(159,184,255,.6)':'0 2px 6px rgba(0,0,0,.3)',
        onTap:()=>this.dotsTap(dt.n) }));
      const byN={}; D.dots.forEach(dt=>byN[dt.n]=dt);
      dotsLine=D.path.map(n=>byN[n].x+','+byN[n].y).join(' ');
    }
    // word match
    let wordEmoji='', wordSlots=[], wordTiles=[];
    if(isWord && s.word){
      const W=s.word;
      wordEmoji=W.emoji;
      wordSlots=W.word.split('').map((ch,i)=>{ const filled=i<W.built.length;
        return { ch: filled?ch:'', bg: filled?'linear-gradient(180deg,#3DBE9B,#2a9a7c)':'rgba(255,255,255,.08)', border: filled?'rgba(255,255,255,.5)':'rgba(255,255,255,.3)' }; });
      wordTiles=W.letters.map(t=>({ ch:t.ch, op: W.usedIds.includes(t.id)?'.22':'1', onTap:()=>this.wordTap(t.id) }));
    }
    // glyph trace
    let traceDots=[], traceLine='', traceLabel='';
    // React Native: traceRef managed by TracePuzzle component via logic.__traceRef
    this.traceRef = this.__traceRef || { current: null };
    if(isTrace && s.trace){
      const T=s.trace;
      traceLabel='Trace '+Math.min(T.next, T.dots.length)+' of '+T.dots.length;
      traceDots=T.dots.map(dt=>({ n:dt.n, x:dt.x, y:dt.y,
        bg: T.path.includes(dt.n)?'#FFD86B':(dt.n===T.next?'#9FB8FF':'rgba(255,255,255,.85)'),
        ring: dt.n===T.next?'0 0 0 5px rgba(159,184,255,.4), 0 0 18px 5px rgba(159,184,255,.6)':'0 2px 6px rgba(0,0,0,.3)' }));
      const byN={}; T.dots.forEach(dt=>byN[dt.n]=dt);
      const pp=T.path.map(n=>byN[n].x+','+byN[n].y);
      if(T.drawing && T.cursor) pp.push(T.cursor.x+','+T.cursor.y);
      traceLine=pp.join(' ');
    }
    // odd one out
    let oddCells=[];
    if(isOdd && s.odd){ oddCells=s.odd.cells.map(c=>({ i:c.i, emoji:c.emoji, onTap:()=>this.oddTap(c.i) })); }
    // counting
    let countItems=[], countOptions=[], countEmoji='';
    if(isCount && s.count){ countEmoji=s.count.emoji; countItems=s.count.items.map(i=>({ x:i.x, y:i.y, rot:i.rot })); countOptions=s.count.options.map(v=>({ v, onTap:()=>this.countPick(v) })); }
    // maze
    let mazeCells=[];
    if(isMaze && s.maze){
      const M=s.maze;
      for(let r=0;r<M.N;r++){ for(let c=0;c<M.N;c++){
        const wall=M.grid[r][c]===1; const isTok=M.pos[0]===r&&M.pos[1]===c; const isGoal=M.goal[0]===r&&M.goal[1]===c;
        mazeCells.push({ token:isTok,
          bg: wall?'#3a2a1c':(isGoal?'radial-gradient(circle,#FFF6DA,#FFD86B)':'rgba(255,248,239,.85)'),
          glow: isGoal?'0 0 12px 3px rgba(255,216,107,.7)':'inset 0 0 0 1px rgba(0,0,0,.08)' });
      } }
    }
    const attemptDots=[0,1,2].map(i=>({ color: i<Math.min(3,s.attempts)?'#E8654E':'rgba(255,255,255,.35)' }));
    const hintText = s.hintText || pg.discovery[0];

    // reward
    const rewardStars=[0,1,2];

    // creatures
    const creatureCards = this.creatureOrder.map(id=>{ const c=this.creatures[id]; const b=s.bonds[id]||0; return { id, name:c.name, species:c.species, archetype:c.archetype, body:c.body, glow:c.glow, accent:c.accent, bond:b, stage:b<30?1:(b<70?2:3), onTap:()=>this.openDetail(id) }; });

    // detail
    const dId=s.detailId; const d=this.creatures[dId]; const db=s.bonds[dId]||0; const dStage=db<30?1:(db<70?2:3);
    const dc={ name:d.name, species:d.species, archetype:d.archetype, biome:d.biome, personality:d.personality, voice:d.voice,
      body:d.body, glow:d.glow, accent:d.accent, bond:db,
      passiveName:d.passiveName, passiveDesc:d.passiveDesc, activeName:d.activeName, activeBond:d.activeBond, activeDesc:d.activeDesc };
    const dcStages=d.stages.map((st,i)=>({ name:st.name, desc:st.desc, ring:(i+1)===dStage?'2.5px solid '+d.accent:'none', op:(i+1)<=dStage?'1':'.5', sat:(i+1)<=dStage?'1':'.4' }));
    const dcLines=d.lines;
    const dcMilestones=d.milestones.map(m=>({ at:m.at, t:m.t, op: db>=m.at?'1':'.55', bg: db>=m.at?d.accent:'#efe6d6', fg: db>=m.at?'#fff':'#9a8a76' }));

    // sanctuary
    const sanctuaryZones=this.creatureOrder.map(id=>{ const c=this.creatures[id]; const b=s.bonds[id]||0; const need=id==='sol'?100:10; const unlocked=b>=need;
      return { home:c.name+'\u2019s Home', body:c.body, glow:c.glow, status: unlocked?'Open \u00b7 Bond '+b:'Locked \u00b7 Bond '+need, op:unlocked?'1':'.55', hasGift: unlocked && s.gifts[id], onGift:()=>this.collectGift(id) }; });
    const decorItems=this.decor;

    // journey
    const curRank=this.rankForXp(s.xp); const nextR=this.nextRank(s.xp);
    const rankNum=curRank.num; const rankName=curRank.name;
    const xpInto = nextR ? (s.xp - curRank.xp) : 1; const xpSpan = nextR ? (nextR.xp - curRank.xp) : 1;
    const xpPct = nextR ? Math.max(4, Math.min(100, Math.round(xpInto/xpSpan*100))) : 100;
    const xpToNext = nextR ? (nextR.xp - s.xp) : 0;
    const rankLadder=this.ranks.map(r=>{ const reached=s.xp>=r.xp; const current=r.num===rankNum;
      return { num:r.num, name:r.name, xp:r.xp, reached, rowBg: current?'#eaf2ec':'transparent', dotBg: reached?'linear-gradient(180deg,#5EA862,#3f7d47)':'#e7ddcb', dotFg: reached?'#fff':'#9a8a76' }; });
    const scrap=this.scrapbook.map(c=>({ label:c.label, bg:c.bg, op:c.earned?'1':'.5', earned:c.earned, locked:!c.earned }));
    const ageBands=[{lo:4,hi:7,label:'4\u20137'},{lo:8,hi:11,label:'8\u201311'},{lo:12,hi:15,label:'12\u201316'},{lo:16,hi:17,label:'16\u201318'},{lo:18,hi:99,label:'18+'}];
    const ageCoverage=ageBands.map(b=>({ label:b.label, count:this.puzzleCodexList.filter(p=>p.ageMin<=b.hi && p.ageMax>=b.lo).length }));
    const codexCards=this.puzzleCodexList.map(p=>({ type:p.type, name:p.name, skill:p.skill, color:p.color, colorDark:p.colorDark,
      ages: p.ageMax>=99 ? ('Ages '+p.ageMin+'+') : ('Ages '+p.ageMin+'\u2013'+p.ageMax), hard:!!p.hard, hardOp:p.hard?'1':'0',
      guideName:this.creatures[p.guide].name, onPlay:()=>this.startPuzzleType(p.type, p.guide, true) }));
    const questCards=s.quests.map(q=>({ id:q.id, type:q.type, title:q.title, color:q.color, prog:q.prog, target:q.target,
      reward:'+'+q.amt+' '+(q.kind==='acorns'?'Acorns':q.kind==='glow'?'Glow Dust':'XP'),
      pct: Math.min(100, Math.round(q.prog/q.target*100)), done:q.claimed, countLabel:q.prog+' / '+q.target }));

    // nav
    const navDefs=[ {key:'map',label:'Map',c:'#5EA862'},{key:'creatures',label:'Friends',c:'#E8822F'},{key:'sanctuary',label:'Home',c:'#4FB8CE'},{key:'journey',label:'Journey',c:'#9B59B6'} ];
    const navItems=navDefs.map(n=>{ const active=scr===n.key; return { label:n.label, onTap:()=>this.go(n.key), color: active?'#3a2a1c':'#b3a695', iconBg: active?n.c:'#d8ccb9', iconShadow: active?'0 4px 10px -4px '+n.c:'none' }; });

    // finale cinematic
    const fst=s.finaleStage;
    const finaleStars=[]; for(let i=0;i<70;i++){ finaleStars.push({ x:(i*37%100), y:(i*53%62), s: 1+(i%3), dur: 2.4+(i%5)*0.6, delay:(i%9)*0.3, op: fst>=1 ? (0.5+(i%5)*0.1).toFixed(2) : '0' }); }
    const finaleGuides=this.creatureOrder.map((id,i)=>{ const c=this.creatures[id]; return { id, body:c.body, glow:c.glow, x: 18+i*12.8, delay: (0.15*i).toFixed(2) }; });
    const finaleCaption = fst<=0 ? 'The constellation is complete…' : fst===1 ? 'One by one, the stars remember their names…' : fst===2 ? 'And the six friends gather beneath the waking sky.' : fst===3 ? '“You traced the last constellation. The Long Night ends.” — Nori' : fst===4 ? '“The forest remembers this moment. It is now part of its long story.” — Sol' : 'The forest is awake. And you are never truly alone in it.';
    const finaleShowTitle = fst>=5;
    const finaleGuidesOp = fst>=2 ? '1' : '0';
    const finaleMoonA = fst>=1 ? '0.85' : '0.2';
    const finaleEnded = fst>=5;
    const finaleShowSkip = fst<5;
    const finaleHasReplay = !!s.finaleSeen;

    // ---- seasonal event ----
    const eventEmojis={ flood:'\ud83c\udf0a', recall:'\u26c8\ufe0f', rising:'\ud83d\udca7', bridge:'\ud83c\udf08', glyph:'\ud83c\udf00' };
    const eventTrials=this.eventTrialDefs.map(t=>{ const g=this.creatures[t.guide]; const done=!!s.eventDone[t.id];
      return { id:t.id, name:t.name, sub:t.sub, pearls:t.pearls, emoji:eventEmojis[t.id]||'\ud83d\udca7', body:g.body, glow:g.glow, done, playable:!done, onPlay:()=>this.startEventTrial(t.id) }; });
    const eventCleared=this.eventTrialDefs.filter(t=>s.eventDone[t.id]).length;
    const eventPct=Math.round(eventCleared/this.eventTrialDefs.length*100);
    const eventAllDone=eventCleared===this.eventTrialDefs.length;
    const eventShop=this.eventShopDefs.map(i=>{ const owned=!!s.eventOwned[i.id]; return { id:i.id, name:i.name, sub:i.sub, cost:i.cost, color:i.color, owned, buyable:!owned, onBuy:()=>this.buyEvent(i.id) }; });
    const rainDrops=[]; for(let i=0;i<14;i++){ rainDrops.push({ x:(i*53%100), dur:(0.7+(i%5)*0.15).toFixed(2), delay:(i%7*0.22).toFixed(2) }); }

    // ---- boss ----
    const bs=s.boss||{};
    const bossHearts=[0,1,2].map(i=>({ bg: i<(bs.hp||0)?'linear-gradient(90deg,#FF5252,#FFB74D)':'rgba(255,255,255,.18)', glow: i<(bs.hp||0)?'0 0 10px 2px rgba(255,120,80,.6)':'none' }));
    const bossOptions=(bs.options||[]).map(sym=>({ sym, onTap:()=>this.bossStrike(sym) }));
    const bossAnim = bs.flash ? 'fq-shake .4s ease' : 'fq-bob 2.4s ease-in-out infinite';

    // ---- daily chest ----
    const dailyDays=this.dailyRewards.map(rr=>{ const isToday=rr.day===1; const claimed=isToday && !!s.dailyClaimed;
      return { day:rr.day, icon:rr.icon, label:rr.label, claimed,
        bg: isToday?'#fff4d8':'#f3ead9', ring: isToday?'2.5px solid #F5A623':'none', shadow:'0 4px 10px -6px rgba(80,60,40,.4)',
        dayColor: isToday?'#b5660c':'#9a8a76', labelColor:'#6a5a48' }; });
    const dailyCanClaim=!s.dailyClaimed;
    const dailyClaimedToday=!!s.dailyClaimed;

    // ---- parent dashboard ----
    const safetyBadges=['No ads','No data collected','COPPA-safe'];
    const parentStats=[
      { value:s.minutesPlayed+' min', label:'Played this week', color:'#56A0D3' },
      { value:String(s.puzzlesSolved), label:'Puzzles solved', color:'#5EA862' },
      { value:regionsOpen+' / 11', label:'Regions explored', color:'#E8954E' },
      { value:'Rank '+rankNum, label:rankName, color:'#9B59B6' }
    ];
    const skillOrder=['Visual','Literacy','Numeracy','Memory','Logic','Motor'];
    const maxSkill=Math.max(1,...skillOrder.map(k=>s.skills[k]||0));
    const parentSkills=skillOrder.map(k=>({ name:k, count:s.skills[k]||0, pct:Math.round((s.skills[k]||0)/maxSkill*100), color:this.skillColors[k] }));
    let favId=this.creatureOrder[0]; this.creatureOrder.forEach(id=>{ if((s.bonds[id]||0)>(s.bonds[favId]||0)) favId=id; });
    const favC=this.creatures[favId]; const favName=favC.name, favBody=favC.body, favGlow=favC.glow, favBond=s.bonds[favId]||0;

    return {
      isTitle:scr==='title', isMap:scr==='map', isRegion:scr==='region', isPuzzle:scr==='puzzle', isReward:scr==='reward',
      isCreatures:scr==='creatures', isDetail:scr==='detail', isSanctuary:scr==='sanctuary', isJourney:scr==='journey', isFinaleScreen:scr==='finale',
      isEvent:scr==='event', isBoss:scr==='boss', isParent:scr==='parent',
      eventTrials, eventCleared, eventPct, eventAllDone, eventShop, rainDrops, rainPearls:s.rainPearls, eventDays:14,
      bs, bossHearts, bossOptions, bossAnim,
      rwIsEvent:!!(s.rw&&s.rw.isEvent), openEvent:()=>this.openEvent(),
      dailyOpen:s.dailyOpen, dailyDays, dailyCanClaim, dailyClaimedToday, claimDaily:()=>this.claimDaily(), closeDaily:()=>this.closeDaily(), openDaily:()=>this.openDaily(),
      safetyBadges, parentStats, parentSkills, favName, favBody, favGlow, favBond, openParent:()=>this.openParent(),
      finaleStars, finaleGuides, finaleCaption, finaleGuidesOp, finaleMoonA, finaleShowTitle, finaleEnded, finaleShowSkip,
      finaleSkip:()=>this.finaleSkip(), finaleDone:()=>this.finaleDone(),
      finaleHasReplay, playFinale:()=>this.playFinale(),
      statusColor, showHud:hub, showNav:hub, navItems,
      acorns:s.acorns, glowDust:s.glowDust,
      begin:()=>this.begin(), goMap:()=>this.go('map'), goCreatures:()=>this.go('creatures'),
      fireflies, rewardSparks, embers,
      mapNodes, mapPoints, regionsOpen,
      riOpen:s.riOpen, ri, closeRi:()=>this.setState({riOpen:false}),
      cr, gc, farX, midX, nearX, markerLeft, exploreProgress:ep, showCollectible, collectibleLeft:42, avatarLine, moveLabel,
      move:()=>this.move(),
      puzzleTitle, isColour, isMemory, isFlow, isDemo, cmBuckets, cmTray, cmEmpty, memCards, memMoves, flowCells,
      isShape, isSequence, isWeight, isLight, isShadow, isRune, isRecall, shapeSlots, shapeTray, seqTiles, seqHint,
      isNumber, isSlide, isHanoi, isEqn, numSeq, numOptions, slideTiles, hanoiPegs, eqnA, eqnB, eqnTarget, eqnOptions,
      isDots, dotsList, dotsLine, dotsLabel,
      isWord, wordEmoji, wordSlots, wordTiles,
      isTrace, traceDots, traceLine, traceLabel, traceRef:this.traceRef,
      traceDown:(e)=>this.traceDown(e), traceMove:(e)=>this.traceMove(e), traceUp:()=>this.traceUp(),
      isOdd, oddCells, isCount, countItems, countOptions, countEmoji,
      isMaze, mazeCells, mazeUp:()=>this.mazeMove(-1,0), mazeDown:()=>this.mazeMove(1,0), mazeLeft:()=>this.mazeMove(0,-1), mazeRight:()=>this.mazeMove(0,1),
      markerPuzzleName, showPuzzleTier, puzzleTierLabel, puzzleTierColor,
      wgtWeights, wgtPlaced, wgtSum, wgtTarget, wgtTilt,
      lightMirrors, lightGem, lightGemGlow, lightHintOp, shadowCurDeg, shadowTargetDeg,
      runeSymbol, runeOpts, runeProgress, recallPads, recallLabel, recallIntro, recallCols, recallSize, recallRadius,
      pgName:pg.name, pgBody:pg.body, pgGlow:pg.glow,
      demoName, demoDesc, demoSkill, solveDemo:()=>this.solveDemo(), exitPuzzle:()=>this.exitPuzzle(),
      attemptDots, hintOpen:s.hintOpen, hintText, toggleHint:()=>this.toggleHint(),
      isLadderPuzzle, ladderLabel, rewardBtnLabel, rwHasProg,
      rw:s.rw||{}, rewardStars, rewardContinue:()=>this.rewardContinue(),
      creatureCards,
      dc, dcStages, dcLines, dcMilestones, addBond:()=>this.addBond(),
      sanctuaryZones, decorItems,
      rankNum, rankName, xpPct, xpInto, xpSpan, xpToNext, xpTotal:s.xp, nextRankName: nextR?nextR.name:'Max', quests:questCards, rankLadder, scrapbook:scrap, puzzleCodexList:codexCards, ageCoverage, finaleHasReplay2:finaleHasReplay,      toastShow:!!s.toast, toastText:s.toast||''
    };
  }

  puzzleDesc(t){
    const m={ flow:'Rotate pipe segments to connect the water source to its destination. Tap a piece to turn it 90\u00b0.',
      light:'Rotate crystals and mirrors to bend a beam of light onto every glowing target.',
      shadow:'Rotate a 3D object until its shadow matches the silhouette on the cavern wall.',
      wind:'Read the wind currents and trace a safe path through the swirling autumn leaves.',
      mechanical:'Set the windmill cogs turning in the right order to open the sky bridge.',
      rune:'Decipher the ancient symbols by matching patterns to the runes you\u2019ve learned.',
      hydraulic:'Route the monsoon water into the correct tanks before the flood rises.',
      final:'Sol\u2019s last teaching \u2014 a multi-stage puzzle that uses every skill you\u2019ve learned.' };
    return m[t]||'A hand-crafted challenge tuned so every child succeeds eventually.';
  }
}

export { Component };
